import {retrieve} from './ai-search.js';
let auth,identity,host,controller,manifest,state,busy=false;
const storageKey=uid=>'aoi-assistant:'+uid;
function newConversationId(){if(crypto.randomUUID)return crypto.randomUUID();const bytes=crypto.getRandomValues(new Uint8Array(16));bytes[6]=bytes[6]&15|64;bytes[8]=bytes[8]&63|128;const hex=[...bytes].map(b=>b.toString(16).padStart(2,'0')).join('');return [hex.slice(0,8),hex.slice(8,12),hex.slice(12,16),hex.slice(16,20),hex.slice(20)].join('-')}
export function cancelAiGuide(){controller?.abort();busy=false}
function load(uid){try{const saved=JSON.parse(localStorage.getItem(storageKey(uid)));if(saved?.conversationId&&Array.isArray(saved.messages))return {...saved,messages:saved.messages.slice(-30)}}catch{}return {conversationId:newConversationId(),messages:[]}}
function save(){try{localStorage.setItem(storageKey(identity),JSON.stringify(state))}catch{state.messages=state.messages.slice(-12);try{localStorage.setItem(storageKey(identity),JSON.stringify(state))}catch{}}}
const $=s=>host.querySelector(s);
function factsView(facts){const {h}=auth;return (facts||[]).map(f=>`<article class="assistant-fact"><h3>${h(f.title)}</h3><p>${h(f.summary||(f.labels||[]).join('、'))}</p><details><summary>查看來源</summary><p>${h(f.source)}</p><pre>${h(f.text)}</pre>${f.shard?`<a href="data/ai/${h(f.shard)}" target="_blank" rel="noopener">原始資料 ↗</a>`:''}</details></article>`).join('')}
function paint(){const {h}=auth;$('#assistant-messages').innerHTML=state.messages.length?state.messages.map(m=>`<div class="assistant-message ${m.role==='user'?'from-player':'from-helper'}">${m.text?`<p>${h(m.text)}</p>`:''}${factsView(m.facts)}</div>`).join(''):'<div class="assistant-message from-helper"><p>想找材料、查配方，還是準備挑戰？問我吧！</p></div>';$('#assistant-messages').scrollTop=$('#assistant-messages').scrollHeight;$('#assistant-send').disabled=busy||!auth.active||!auth.cfg.aiEndpoint;$('#assistant-search').disabled=busy;$('#assistant-new').disabled=busy;$('#assistant-status').textContent=busy?'小助手正在查資料…':!auth.active?'登入玩家帳號後就能聊天；也可以先搜尋。':''}
export function openAssistant(){if(!host)return;$('#assistant-window').hidden=false;$('#assistant-launcher').setAttribute('aria-expanded','true');$('#assistant-input').focus()}
function closeAssistant(){$('#assistant-window').hidden=true;$('#assistant-launcher').setAttribute('aria-expanded','false');$('#assistant-launcher').focus()}
export function syncAssistant(options){auth=options;const uid=options.user?.id||'guest';if(host&&uid===identity){paint();return}cancelAiGuide();identity=uid;state=load(uid);host?.remove();host=document.createElement('aside');host.id='assistant-host';document.body.append(host);host.innerHTML=`<button id="assistant-launcher" aria-expanded="false" aria-controls="assistant-window"><span aria-hidden="true">✦</span> 問問小助手</button><section id="assistant-window" role="dialog" aria-labelledby="assistant-title" hidden><header class="assistant-header"><h2 id="assistant-title">問問小助手</h2><div><button id="assistant-new" title="開始新對話" aria-label="開始新對話">＋</button><button id="assistant-close" aria-label="縮小聊天室">－</button></div></header><div id="assistant-messages" role="log" aria-live="polite"></div><p id="assistant-status" role="status"></p><form id="assistant-form"><label class="assistant-input-label" for="assistant-input">訊息</label><textarea id="assistant-input" maxlength="600" rows="2" placeholder="問問配方、材料或取得方式…" required></textarea><div class="assistant-actions"><button id="assistant-search" type="button">搜尋</button><button id="assistant-send" class="primary" type="submit">傳送 ➤</button></div></form></section>`;
 $('#assistant-launcher').onclick=()=>$('#assistant-window').hidden?openAssistant():closeAssistant();$('#assistant-close').onclick=closeAssistant;$('#assistant-new').onclick=()=>{state={conversationId:newConversationId(),messages:[]};save();paint();$('#assistant-input').focus()};$('#assistant-form').onsubmit=e=>{e.preventDefault();send(true)};$('#assistant-search').onclick=()=>send(false);$('#assistant-input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();if(!$('#assistant-send').disabled)send(true)}};host.onkeydown=e=>{if(e.key==='Escape'&&!$('#assistant-window').hidden)closeAssistant()};paint()}
export function mountAiGuide(){openAssistant()}
async function send(ai){const question=$('#assistant-input').value.trim();if(!question||busy||ai&&(!auth.active||!auth.cfg.aiEndpoint))return;const owner=identity,snapshot=auth;controller=new AbortController();const signal=controller.signal;busy=true;state.messages.push({role:'user',text:question});$('#assistant-input').value='';save();paint();
 try{let facts=[],text='';if(ai){const session=await snapshot.db.auth.getSession();if(identity!==owner||signal.aborted)return;const token=session.data?.session?.access_token;if(!token||session.data.session.user.id!==owner)throw Error('請重新登入玩家帳號。');const response=await fetch(snapshot.cfg.aiEndpoint.replace(/\/$/,'')+'/ask',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({question,conversationId:state.conversationId}),signal:AbortSignal.any([signal,AbortSignal.timeout(90000)])});const answer=await response.json();if(!response.ok)throw Error(answer.error||'小助手暫時無法回覆，試試搜尋。');facts=answer.facts||[];text=facts.length?'找到這些資料：':'沒有找到足夠的資料，可以換個名稱問問看。';if(identity===owner)host.dataset.provider=answer.provider||'none'}else{const read=async file=>{const r=await fetch('data/ai/'+file,{signal});if(!r.ok)throw Error('資料暫時無法讀取。');return r.json()};manifest??=await read('manifest.json');facts=await retrieve(manifest,question,read);facts=facts.slice(0,5);text=facts.length?'搜尋到這些資料：':'沒有找到資料，試試物品中文名或原文名。'}if(identity!==owner||signal.aborted)return;state.messages.push({role:'assistant',text,facts});state.messages=state.messages.slice(-30);save();
 }catch(e){if(identity===owner&&!signal.aborted){state.messages.push({role:'assistant',text:e.name==='TimeoutError'?'等候較久，請稍後再試。':e.message});save()}}finally{if(identity===owner&&!signal.aborted){busy=false;paint()}}}
