import {retrieve} from './ai-search.js';
let controller=null;
export function cancelAiGuide(){controller?.abort();controller=null}
export function mountAiGuide(root,{h,db,active,cfg}){
 controller?.abort();controller=new AbortController();const signal=controller.signal;
 const endpoint=cfg.aiEndpoint||'';let sequence=0,manifest;
 root.innerHTML=`<section class="ai-guide"><h1>問攻略</h1><p>查詢本包的解包資料，包含配方、掉落、生成與模組內建手冊。</p><form class="ai-question"><label for="ai-question">你的問題</label><textarea id="ai-question" maxlength="600" rows="3" placeholder="例如：魔法之眼在哪裡取得？" required></textarea><div class="ai-actions"><button type="submit" class="primary" ${!endpoint||!active?'disabled':''}>詢問 AI</button><button type="button" id="ai-search">搜尋解包資料</button></div></form><p class="ai-availability">${!endpoint?'雲端問答尚未啟用；解包資料搜尋已可使用。':!active?'登入並通過玩家審核後即可提問。':'每人每日最多 50 次，全站每日最多 400 次；免費額度用完後仍可搜尋。'}</p><p class="ai-privacy">提問會傳送至雲端 AI 服務。請勿輸入密碼或私人資料。</p><p id="ai-status" role="status" aria-live="polite"></p><div id="ai-answer"></div><div id="ai-results"></div><details><summary>解包範圍與資料限制</summary><p>伺服器設定與資料包可能覆寫模組預設資料。程式反編譯與問答索引的完成狀態分開記錄。</p><a href="data/ai/coverage.json" target="_blank" rel="noopener">查看逐模組查核清單</a></details></section>`;
 const $=s=>root.querySelector(s),read=async file=>{const r=await fetch('data/ai/'+file,{signal});if(!r.ok)throw Error('解包資料尚未準備好。');return r.json()};
 const display=facts=>facts.map(f=>`<article class="ai-fact"><h3>${h(f.title)}</h3><p>${h((f.labels||[]).join('、'))}</p>${f.summary?`<p>${h(f.summary)}</p>`:''}<details><summary>查看詳細資料與依據</summary><pre>${h(f.text)}</pre><p>${h(f.jar)}<br>${h(f.source)} · ${h(f.pointer)}</p><a href="data/ai/${h(f.shard||'')}" target="_blank" rel="noopener">解包資料檔</a></details></article>`).join('');
 async function search(q,id){manifest??=await read('manifest.json');const facts=await retrieve(manifest,q,async file=>(await read(file)).map(f=>({...f,shard:file})));if(id!==sequence||signal.aborted||!root.isConnected)return;$('#ai-results').innerHTML='<h2>解包搜尋結果</h2>'+(facts.length?display(facts):'<p>找不到資料；試試物品中文名、原文名或註冊 ID。</p>');return facts}
 async function run(ai){const q=$('#ai-question').value.trim();if(!q)return;const id=++sequence;$('#ai-status').textContent=ai?'正在查詢解包依據…':'正在搜尋…';$('#ai-answer').innerHTML='';root.querySelectorAll('.ai-actions button').forEach(b=>b.disabled=true);
 try{await search(q,id);if(ai){const session=await db.auth.getSession();const token=session.data?.session?.access_token;if(!token)throw Error('請重新登入。');const r=await fetch(endpoint.replace(/\/$/,'')+'/ask',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({question:q}),signal:AbortSignal.any([signal,AbortSignal.timeout(90000)])});const answer=await r.json();if(!r.ok)throw Error(answer.error||'雲端問答暫時無法使用。');if(id!==sequence||signal.aborted||!root.isConnected)return;$('#ai-answer').innerHTML='<h2>AI 找到的依據</h2><p>'+h(answer.message||'')+'</p>'+display(answer.facts||[]);$('#ai-status').textContent=answer.remaining===undefined?'查詢完成。':`查詢完成，今日剩餘 ${answer.remaining} 次。`}else $('#ai-status').textContent='搜尋完成。';
 }catch(e){if(e.name!=='AbortError'&&!signal.aborted&&id===sequence&&$('#ai-status'))$('#ai-status').textContent=e.message}finally{if(!signal.aborted&&id===sequence&&$('#ai-search')){$('#ai-search').disabled=false;$('.primary').disabled=!endpoint||!active}}}
 $('.ai-question').onsubmit=e=>{e.preventDefault();run(true)};$('#ai-search').onclick=()=>run(false);
}
