import {avatarImage,openAvatarEditor,resolveAvatars} from './avatar.js';
import {createRecipeView} from './recipe-view.js';
import {tagName,stationName,heatName} from './recipe-labels.js';
import {createClient} from '@supabase/supabase-js';
import {readGuide,writeGuide} from './guide-progress.js';
import {mountKeyGuide,KEY_VERSION} from './key-guide.js';
const $=s=>document.querySelector(s),h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),enc=encodeURIComponent;
const CATEGORIES={equipment:'裝備',skills:'技能與法術',bosses:'首領與事件',companions:'夥伴與坐騎',strategy:'實戰攻略',advancements:'成就'};
const NAV=[['home','▥','世界'],['collections','⚒','圖鑑'],['team','⚑','隊伍'],['me','▣','我的']];
function navIcon(id){const art={home:'<path d="M1 13V9h2V7h2V4h2V2h2v3h2v3h2v2h2v3z"/><path fill="var(--surface)" d="M6 5h1V3h1v3h2v2H6z"/>',collections:'<path d="M3 2h9v1h1v11H3v-1H2V3h1z"/><path fill="var(--surface)" d="M4 3h1v10H4zm3 2h4v1H7zm0 3h4v1H7zm0 3h3v1H7z"/>',team:'<path d="M6 2h4v4H6zM2 5h3v3H2zm9 0h3v3h-3zM5 8h6v6H5zM1 10h3v4H1zm11 0h3v4h-3z"/>',me:'<path d="M2 2h12v12H2z"/><path fill="var(--surface)" d="M4 5h3v3H4zm5 0h3v3H9zM7 8h2v2H7zm-2 2h6v3H9v-1H7v1H5z"/>'};return `<svg class="pixel-nav-icon" viewBox="0 0 16 16" width="28" height="28" fill="currentColor" shape-rendering="crispEdges" aria-hidden="true">${art[id]}</svg>`}
const GROUPS=[['起步','▣','熟悉世界','操作、地圖、補給與救援'],['定居','▥','建立家園','殖民地、居民、建設與防衛'],['生產','⚒','鋼鐵產業','動力、加工、倉儲與物流'],['旅行','↗','連結疆域','鐵路、船舶、跑酷與飛行'],['戰鬥','⚔','掌握秘法','武器、技能、法術與配裝'],['探索','♜','踏入未知','地牢、首領、夥伴與終界'],['協作','⚑','共建帝國','隊伍、需求與遠征邀約'],['收藏','✦','留下足跡','圖鑑、成就與完成進度']];
let cfg,db,articles,collections,advancements,icons,summary,recipes,originals,names,materialTags,keyGuide,requestItems;
let user=null,active=false,isAdmin=false,cloudUnavailable=false,profile=null,world=null,progress=new Map(),teams=[],teamId='',channel=null,teamRows=[],requests=[],teamRecords=[],players=new Map(),currentGuide=null,pageNumber=1;
let routeSequence=0,guideTimer,authBusy=false,teamMembers=[];
let booting=true,skipIntro=false;
let keyReturn="me";
 const entryStarted=performance.now(),initialHash=location.hash;
const reduceEntryMotion=()=>document.documentElement.dataset.motion==='off'||matchMedia('(prefers-reduced-motion: reduce)').matches;
function dismissIntro(immediate=false){
 const intro=$('#intro');skipIntro=true;booting=false;document.body.classList.remove('booting');
 if(!intro)return;
 intro.classList.add('intro-ready','intro-quiet');
 if(immediate){intro.remove();$('#main')?.focus({preventScroll:true});return}
 intro.classList.add('intro-leaving');setTimeout(()=>{intro.remove();$('#main')?.focus({preventScroll:true})},180);
}
async function finishIntro(){
 const intro=$('#intro');if(!intro){booting=false;document.body.classList.remove('booting');return}
 while(!skipIntro&&!reduceEntryMotion()&&performance.now()-entryStarted<4600)await new Promise(r=>setTimeout(r,50));
 if(skipIntro){dismissIntro(true);return}
 intro.classList.add('intro-ready');booting=false;document.body.classList.remove('booting');
 if(!reduceEntryMotion()){intro.classList.add('intro-leaving');await new Promise(r=>setTimeout(r,650));}
 intro.remove();if(document.activeElement===document.body)$('#main').focus({preventScroll:true});
}
$('#intro-skip')?.addEventListener('click',()=>dismissIntro(true));
setTimeout(()=>{if(booting)dismissIntro(true)},8000);
const app=$('#main');
function toast(message,error=false){const e=document.createElement('div');e.className='toast'+(error?' error':'');e.textContent=message;$('#toasts').append(e);setTimeout(()=>e.remove(),3500)}
function check(r){if(r.error)throw Error(r.error.message);return r.data}
function showError(e){toast(e.message||'暫時無法完成，請再試一次',true)}
function inventoryControls(root){for(const el of root.querySelectorAll('.item-link')){if(!el.querySelector('img')||el.dataset.itemHint)continue;const label=el.textContent.trim();el.dataset.itemHint=label;el.setAttribute('aria-label',label);for(const node of [...el.childNodes])if(node.nodeType===Node.TEXT_NODE){const span=document.createElement('span');span.className='inventory-label';span.textContent=node.textContent;node.replaceWith(span)}}}
function modal(title,body,itemId){$('#modal').classList.remove('boss-dialog');delete $('#modal').dataset.requestId;$('#modal-title').textContent=title;if(itemId&&icons[itemId])$('#modal-title').innerHTML=`<span class="item-title-icon" tabindex="0" data-item-hint="${h(title)}" aria-label="${h(title)}">${image(itemId)}</span>`;$('#modal-body').innerHTML=body;inventoryControls($('#modal-body'));if(!$('#modal').open)$('#modal').showModal()}
function keyState(){const remote=progress.get('settings:keys-'+KEY_VERSION)?.checklist;try{const local=JSON.parse(localStorage.getItem('iaa-keys-'+(user?.id||'guest')+'-'+KEY_VERSION)||'null');return ['complete','skipped'].includes(remote?.status)?remote:local||remote||{checks:{}}}catch{return remote||{checks:{}}}}
function rememberKeys(state){try{localStorage.setItem('iaa-keys-'+(user?.id||'guest')+'-'+KEY_VERSION,JSON.stringify(state))}catch{}}
function needsKeySetup(){return !['complete','skipped'].includes(keyState().status)}
function keysPage(){mountKeyGuide(app,{data:keyGuide,h,image,saved:keyState().checks,onSave:checks=>rememberKeys({status:'in-progress',checks}),onFinish:(status,checks)=>{const state={status,checks};rememberKeys(state);if(active)saveRecord('settings:keys-'+KEY_VERSION,{checklist:state,completed:status==='complete'}).catch(showError);go(keyReturn)}})}
function closeModal(){$('#modal').close()}
function route(){const hash=location.hash.slice(1)||'home',i=hash.indexOf('?');return {path:(i<0?hash:hash.slice(0,i)).split('/').map(decodeURIComponent),q:new URLSearchParams(i<0?'':hash.slice(i+1))}}
function go(path){location.hash=path}
const empty=text=>`<div class="empty">${h(text)}</div>`;
const notice=(text,warn=false)=>`<div class="notice${warn?' warn':''}">${h(text)}</div>`;
function percent(done,total){return total?Math.round(done/total*100):0}
function bar(done,total){return `<div class="progressbar"><span style="width:${percent(done,total)}%"></span></div><small>${done} / ${total} · ${percent(done,total)}%</small>`}
function image(id,cls=''){return icons[id]?`<img class="${cls}" src="${h(icons[id])}" alt="" loading="lazy" width="48" height="48">`:''}
function heading(title){return `<div class="page-heading"><h1>${h(title)}</h1></div>`}
function breadcrumb(title){return `<div class="breadcrumb"><a href="#home">世界</a> / ${h(title)}</div>`}
function atlasBreadcrumb(parts){
 const rows=Array.isArray(parts)?parts:[parts];
 return `<div class="breadcrumb"><a href="#collections">圖鑑</a>${rows.map((part,i)=>{const item=typeof part==='string'?{label:part}:part;return ' / '+(item.href&&i<rows.length?'<a href="'+h(item.href)+'">'+h(item.label)+'</a>':h(item.label))}).join('')}</div>`;
}
function finished(key){return !!progress.get(key)?.completed}
function wanted(key){return !!progress.get(key)?.checklist?.wish}
function wishlistToggle(key,label='加入想收集'){return `<label class="complete-check wishlist-check collection-state-button"><input type="checkbox" data-wish="${h(key)}" ${wanted(key)?'checked':''}><span class="wishlist-symbol" aria-hidden="true"></span><span>${h(label)}</span></label>`}
const JOURNEY_ORDER=['start','land','colony-start','factory','combat','expedition'];
function nextJourneyArticle(){return JOURNEY_ORDER.find(id=>!finished('article:'+id))||JOURNEY_ORDER[JOURNEY_ORDER.length-1]}
function completion(key,label='已完成收藏'){return `<label class="complete-check collection-state-button collection-done-button"><input type="checkbox" data-complete="${h(key)}" ${finished(key)?'checked':''}><span class="done-symbol" aria-hidden="true">✓</span><span>${h(label)}</span></label>`}
function atlasStateButtons(key){return `<div class="atlas-card-state"><label class="atlas-state-icon atlas-wish-icon" title="${wanted(key)?'從我想收集移除':'加入我想收集'}"><input type="checkbox" data-wish="${h(key)}" ${wanted(key)?'checked':''}><span aria-hidden="true">${wanted(key)?'★':'☆'}</span></label><label class="atlas-state-icon atlas-done-icon" title="${finished(key)?'取消已取得':'標記為已取得'}"><input type="checkbox" data-complete="${h(key)}" ${finished(key)?'checked':''}><span aria-hidden="true">✓</span></label></div>`}
function needAccount(){if(active&&user&&world)return true;toast(user?'帳號仍待管理員核准':'請登入已核准的帳號來保存紀錄');openAuth();return false}
function groupFor(ns){if(['minecolonies','supplementaries','webdisplaystogether'].includes(ns))return '定居';if(['create','ae2','vintage','tetra','butchercraft','create_enchantment_industry','createmetallurgy','create_connected','farmersdelight','kaleidoscope_cookery'].includes(ns))return '生產';if(['northstar','railways','createrailwaysnavigator'].includes(ns))return '旅行';if(['irons_spellbooks','efn','slu','bonfires','onekick'].includes(ns))return '戰鬥';if(['alexsmobs','adorablehamsterpets','saintsdragons','dragonsofberk'].includes(ns))return '夥伴';return ns==='minecraft'?'原版':'探索'}
const GROUP_ICONS={'起步':'minecraft:compass','定居':'minecolonies:blockhuttownhall','生產':'create:cogwheel','旅行':'create:track','戰鬥':'irons_spellbooks:iron_spell_book','探索':'minecraft:ender_eye','協作':'minecolonies:supplycampdeployer','收藏':'minecraft:book'};
const recordByKey=()=>new Map([...collections.map(x=>[x.key,x]),...advancements.map(x=>['advancement:'+x.id,{...x,key:'advancement:'+x.id,category:'advancements',collectible:true}])]);
function articleCard(a){const g=GROUPS.find(g=>g[0]===a.group);return `<a class="card card-link" href="#article/${enc(a.id)}"><span class="tag">${h(a.group)}</span><h3>${h(a.title)}</h3><small>${a.steps.length} 個步驟</small></a>`}
function home(){
 const total=collections.filter(x=>x.collectible).length;
 app.innerHTML=`<section class="hero"><img class="hero-art" src="assets/world-panorama.png" alt="龍族、殖民地與水輪工坊"><div class="hero-copy"><h1>${h(cfg.serverNameZh)}</h1><div class="actions"><a class="btn primary" href="#article/${nextJourneyArticle()}">${finished('article:start')?'繼續我的征途':'開始我的征途'} →</a><a class="btn" href="#collections">打開收藏圖鑑</a></div></div></section>
 <div class="stats"><div class="stat"><b>${articles.length}</b><small>玩家教學</small></div><div class="stat"><b>${total.toLocaleString()}</b><small>收藏項目</small></div><div class="stat"><b>${advancements.length.toLocaleString()}</b><small>成就條目</small></div></div>
 <div class="section-head"><h2>今天，想完成什麼？</h2></div><div class="grid cols3">${GROUPS.map(g=>`<a href="#journey/${enc(g[0])}" class="card card-link"><div class="card-icon">${image(GROUP_ICONS[g[0]])}</div><h3>${h(g[2])}</h3><small>${articles.filter(a=>a.group===g[0]).length} 篇手札　→</small></a>`).join('')}</div>
 <div class="section-head"><h2>參考順序</h2></div><div class="trail">${[['start','熟悉新世界','查配方、調按鍵、建立回程路線'],['land','找到家園','選址，留出殖民地與工廠空間'],['colony-start','讓聚落成長','先讓建築工、食物與物流運作'],['factory','讓鋼鐵流動','把材料加工接到基地供應'],['combat','掌握自己的力量','選武器、技能與法術，練習實際操作'],['expedition','把足跡留向遠方','地牢、首領、夥伴與成就']].map((p,i)=>`<a href="#article/${p[0]}"><span class="number">${i+1}</span><span><b>${h(p[1])}</b></span></a>`).join('')}</div>
 <div class="section-head"><h2>你的冒險收藏冊</h2><a href="#collections">全部 →</a></div><div class="grid">${originals.map(x=>`<a class="card card-link" href="#guide/${x.id}"><h3>${h(x.title)}</h3></a>`).join('')}</div>`;
}
function journey(group){const g=GROUPS.find(x=>x[0]===group);app.innerHTML=breadcrumb(g?.[2]||group)+heading(g?.[2]||group,g?.[3]||'依玩家目標串起教學')+`<div class="grid">${articles.filter(a=>a.group===group).map(articleCard).join('')}</div>`}
function article(id){const a=articles.find(x=>x.id===id);if(!a){app.innerHTML=empty('找不到這篇手札');return}
 app.innerHTML=breadcrumb(a.group)+`<article class="article"><span class="tag gold">${h(a.group)}</span><h1>${h(a.title)}</h1><p class="article-intro">${tutorialText(a.intro,a)}</p>${a.items.length?`<section class="preparation"><h3>先準備這些</h3><div class="item-list">${a.items.map(x=>`<button class="item-link" data-recipe="${h(x.id)}">${image(x.id)}${h(x.name)}</button>`).join('')}</div></section>`:''}<ol class="tutorial-steps">${a.steps.map((s,i)=>`<li class="step"><span class="number">${i+1}</span><p>${tutorialText(s,a)}</p></li>`).join('')}</ol><section class="panel"><h2>卡住時先看這裡</h2><ul>${a.troubleshooting.map(x=>`<li>${tutorialText(x,a)}</li>`).join('')}</ul></section><section><h2>下一步可以接到…</h2><div class="grid">${a.related.map(id=>articles.find(x=>x.id===id)).filter(Boolean).map(articleCard).join('')}</div></section>${completion('article:'+a.id,'我已實際完成這篇教學')}<details><summary>查核範圍與參考</summary><p class="muted">${h(a.evidence)}</p>${a.sources.map(s=>`<p><a href="${h(s)}" target="_blank" rel="noopener">官方功能說明 ↗</a></p>`).join('')}</details></article>`;
}
function itemRecipe(id){const d=recipes[id];let html='';if(d?.recipes?.length){html=d.recipes.map(r=>renderRecipe(r.raw)).join('')}else html=notice('沒有找到可直接展示的普通合成配方。此項目可能需要工作站、改造、召喚或其他取得方式；請以遊戲內配方與指南查詢。');modal(d?.name||nameOf(id),html,id)}
function nameOf(id){return recipes[id]?.name||names[id]||collections.find(x=>x.id===id)?.title||id}
function ingredient(v){if(!v)return '';if(typeof v==='string')return nameOf(v);if(Array.isArray(v))return v.map(ingredient).join(' 或 ');if(v.item)return nameOf(v.item)+(v.count?' × '+v.count:'');if(v.tag)return tagName(v.tag)+'（可用材料依遊戲配方選項）';if(v.fluid)return ({'minecraft:water':'水','minecraft:lava':'熔岩'}[v.fluid]||names[v.fluid]||'指定流體')+(v.amount?' '+v.amount+' mB':'');return '此工作站使用的特殊材料，請以遊戲內選項確認'}
function renderRecipe(r){return createRecipeView({h,image,nameOf,tagName,stationName,heatName,tags:materialTags,icons}).renderRecipe(r)}
function materialOptions(tag){const rows=materialTags[tag]||[];modal(tagName(tag),`<div class="item-list">${rows.map(id=>`<button class="item-link" data-recipe="${h(id)}">${image(id)}${h(nameOf(id))}</button>`).join('')||notice('請在遊戲配方頁查看可用材料。')}</div>`,rows.find(id=>icons[id]))}
function tutorialText(text,a){
 const choices=new Map();
 for(const [id,label]of Object.entries(names))if(icons[id]&&label.length>=2&&!label.includes('§'))choices.set(label,id);
 for(const x of a.items)choices.set(x.name,x.id);
 for(const [label,id]of Object.entries({'合成台':'minecraft:crafting_table','普通工作台':'minecraft:crafting_table','工作台':'minecraft:crafting_table','建造工具':'structurize:sceptergold','補給營地':'minecolonies:supplycampdeployer','補給船':'minecolonies:supplyshipdeployer','鐵砧':'minecraft:anvil','攪拌盆':'create:basin','攪拌器':'create:mechanical_mixer','火焰燃燒室':'create:blaze_burner','烈焰燃燒室':'create:blaze_burner','動力沖壓機':'create:mechanical_press','置物台':'create:depot'}))if(icons[id])choices.set(label,id);
 const matches=[...choices.keys()].filter(label=>text.includes(label)).sort((a,b)=>b.length-a.length);
 if(!matches.length)return h(text);
 const pattern=new RegExp(matches.map(label=>label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|'),'g');
 let last=0,out='';for(const m of text.matchAll(pattern)){out+=h(text.slice(last,m.index));const id=choices.get(m[0]);out+=`<button class="inline-item" data-recipe="${h(id)}">${image(id)}<span>${h(m[0])}</span></button>`;last=m.index+m[0].length}return out+h(text.slice(last));
}

const ATLASES=[
 ['equipment','⚒','裝備收藏冊','依系列瀏覽、想收集清單、素材追查、完整配方與掉落來源','equipment'],
 ['skills','✦','技能與法術','功能、持握條件、取得方法、法術學派與參考清單','skills'],
 ['bosses','♜','首領與事件','出現地點、召喚方式、分段戰術、遇見／擊敗／獎勵進度','bosses'],
 ['companions','♥','夥伴','馴服條件、照顧方法、用途與準備進度','bosses'],
 ['mounts','↗','坐騎','坐騎比較、速度與乘騎條件、取得與馴服方法','bosses'],
 ['strategy','⚔','緋紅獵人實戰手冊','章節導覽、整套配裝、增益清單、機制圖解與實戰流程','scarlet'],
 ['advancements','✦','成就全收集','','advancements']
];
const COVER_ITEMS={equipment:'minecraft:diamond_sword',skills:'minecraft:enchanted_book',bosses:'minecraft:nether_star',companions:'minecraft:bone',mounts:'minecraft:saddle',strategy:'minecraft:totem_of_undying',advancements:'minecraft:book'};
function atlasNav(category,noteKey){return noteKey?`<div class="atlas-note-tools"><button data-atlas-note="${h(noteKey)}">私人筆記</button></div>`:''}
function catalog(){const {q}=route(),category=q.get('category')||'',query=q.get('q')||'';
 if(q.get('wishlist')==='1'){wishlistOverview();return}
 if(category==='advancements'){advanceList();return}
 const atlas=ATLASES.find(a=>a[0]===category);
 if(atlas){mountAtlas(atlas,{query,done:q.get('done')||'all',mode:q.get('view')||'all'});return}
 app.innerHTML=heading('冒險收藏圖鑑')+`<a class="wishlist-overview-card" href="#collections?wishlist=1"><span class="wishlist-symbol">☆</span><span><strong>我想收集</strong><small>一次查看所有收藏冊中標記「想收集」的項目</small></span><b>→</b></a><form id="atlas-search" class="filters"><input name="q" aria-label="搜尋全部圖鑑" placeholder="搜尋裝備、技能、首領或夥伴…" value="${h(query)}"><button class="primary">搜尋所有圖鑑</button></form><div class="atlas-shelves">${ATLASES.map(([id,icon,title,desc],i)=>{const rows=id==='advancements'?advancements.map(x=>({...x,key:'advancement:'+x.id})):collections.filter(x=>x.category===(id==='mounts'?'companions':id)&&x.collectible&&(id!=='mounts'||x.mount));return `<a class="atlas-book book-${id}" href="#collections?category=${id}" aria-label="打開${title}"><div class="book-shape"><span class="book-pages" aria-hidden="true"></span><div class="book-cover"><span class="book-spine" aria-hidden="true"></span><span class="book-emblem" aria-hidden="true"><img src="${h(icons[COVER_ITEMS[id]])}" alt="" width="40" height="40"></span><h2>${id==='strategy'?'緋紅獵人<br>實戰手冊':h(title)}</h2></div></div>${id==='strategy'?'':bar(rows.filter(x=>finished(x.key)).length,rows.length)}</a>`}).join('')}</div><section class="shelf-actions"><div class="actions"><a class="btn" href="#team?tab=progress">隊伍收藏比較</a></div></section>`;
 $('#atlas-search').onsubmit=e=>{e.preventDefault();go('search?q='+enc(new FormData(e.target).get('q')))};
}
function wishlistOverview(){
 const all=[...collections.filter(x=>x.collectible),...advancements.map(x=>({...x,key:'advancement:'+x.id,category:'advancements'}))];
 const rows=all.filter(x=>wanted(x.key));
 app.innerHTML=atlasBreadcrumb('我想收集')+heading('我想收集')+`<p class="article-intro">跨收藏冊集中查看你下一步想取得的裝備、技能、首領獎勵、夥伴、坐騎與成就。</p><div class="grid cols3">${rows.map(x=>{const type=x.mount?'坐騎':(CATEGORIES[x.category]||'收藏');return `<button class="card card-link wishlist-entry wishlist-entry-compact" type="button" data-wishlist-open="${h(x.key)}">${image(x.id,'wishlist-entry-image')}<span class="tag">${h(type)}</span><h3>${h(x.title)}</h3></button>`}).join('')||empty('還沒有標記任何想收集項目。打開任一收藏冊，按下 ☆ 加入。')}</div>`;
}
function refreshAtlasReader(frame){
 try{
  const doc=frame?.contentDocument;if(!doc)return;
  const hasCss=[...doc.querySelectorAll('link[rel="stylesheet"]')].some(link=>link.href.includes('atlas-reader.css')&&link.href.includes('20261006-aoi19'));
  const hasJs=[...doc.scripts].some(script=>script.src.includes('atlas-reader.js')&&script.src.includes('20261006-aoi19'));
  if(!hasCss){const link=doc.createElement('link');link.rel='stylesheet';link.href='../atlas-reader.css?v=20261006-aoi19';link.dataset.aoiReader='7';doc.head.append(link)}
  if(!hasJs){const script=doc.createElement('script');script.src='../atlas-reader.js?v=20261006-aoi19';script.defer=true;script.dataset.aoiReader='7';doc.head.append(script)}
 }catch{}
}
function mountAtlas(atlas,options={}){
 const [category,,title,,slug]=atlas,g=originals.find(g=>g.id===slug);
 const saved=progress.get('guide:'+slug)?.checklist||{},data=active?writeGuide(slug,saved,progress,collections):saved,uid=user?.id||'guest';
 for(const [k,v] of Object.entries(data))localStorage.setItem('iaa-guide-'+uid+'-'+slug+'-'+k,v);
 currentGuide={slug,category,...options};
 document.body.classList.add('atlas-open');
 app.innerHTML=atlasNav(category,options.recordKey&&['skills','scarlet'].includes(slug)?options.recordKey:null)+`<div class="reader-loading-indicator" role="status">正在翻開收藏冊…</div><iframe aria-busy="true" class="guide-frame atlas-frame" id="guide-frame" title="${h(title)}" src="${g.path}?player=${enc(uid)}&atlas=${slug}&section=${enc(category)}&reader=20261006-aoi19" allow="clipboard-write"></iframe>`;
 const frame=$('#guide-frame');
 const openPayload=()=>({type:'atlas-open',id:options.item,query:options.query,reference:options.reference,done:options.done,mode:options.mode||'all',view:category==='companions'?'pets':category==='mounts'?'mounts':'boss',wishes:collections.filter(c=>c.sourceGuide===slug&&wanted(c.key)).map(c=>c.id)});
 frame?.addEventListener('load',()=>{
   refreshAtlasReader(frame);
   try{frame.contentWindow.postMessage(openPayload(),location.origin)}catch{}
   setTimeout(()=>{
     if(!frame.isConnected||frame.dataset.ready==='true')return;
     try{delete frame.contentDocument.documentElement.dataset.readerLoading}catch{}
     frame.dataset.ready='fallback';frame.setAttribute('aria-busy','false');
     document.querySelector('.reader-loading-indicator')?.remove();
   },3500);
 },{once:true});
}
function renderPage(rows,target,render){const size=30,last=Math.max(1,Math.ceil(rows.length/size));pageNumber=Math.min(pageNumber,last);$('#'+target).innerHTML=`<p class="result-count">${rows.length.toLocaleString()} 筆 · 第 ${pageNumber} / ${last} 頁</p><div class="grid cols3">${rows.slice((pageNumber-1)*size,pageNumber*size).map(render).join('')}</div>${rows.length?`<div class="pager"><button data-page="${pageNumber-1}" ${pageNumber===1?'disabled':''}>← 上頁</button><span>${pageNumber} / ${last}</span><button data-page="${pageNumber+1}" ${pageNumber===last?'disabled':''}>下頁 →</button></div>`:empty('沒有符合條件的項目，試試不同關鍵字。')}`}
function record(key){const x=collections.find(x=>x.key===key);if(!x){app.innerHTML=empty('找不到收藏項目');return}
 const atlas=ATLASES.find(a=>a[0]===x.category)||ATLASES.find(a=>a[4]===x.sourceGuide);
 if(atlas)mountAtlas(atlas,{item:x.category==='strategy'?x.key.replace('scarlet:',''):x.id,query:x.title,reference:!x.collectible,title:x.title,recordKey:x.key});
 else app.innerHTML=empty('找不到這項收藏的攻略');
}
function notesPanel(key){return `<section class="panel"><h3>我的私人筆記</h3><form data-note="${h(key)}"><textarea aria-label="私人筆記" name="notes" maxlength="8000" placeholder="材料進度、嘗試結果、下一步…">${h(progress.get(key)?.notes||'')}</textarea><button class="primary">保存筆記</button></form></section>`}
function advanceList(){const {q}=route(),needle=q.get('q')||'',group=q.get('group')||'',hidden=q.get('hidden')==='1',done=q.get('done')||'all';
 app.innerHTML=atlasNav('advancements')+heading('成就全收集','查看前置鏈與達成條件，逐步留下你在這個世界的足跡。')+`<form id="advance-filter" class="filters"><input name="q" aria-label="搜尋成就" placeholder="搜尋名稱、物品或條件…" value="${h(needle)}"><select name="group" aria-label="成就領域"><option value="">所有領域</option>${['原版','定居','生產','旅行','戰鬥','探索','夥伴'].map(g=>`<option ${group===g?'selected':''}>${g}</option>`).join('')}</select><select name="done" aria-label="成就完成狀態"><option value="all">所有進度</option><option value="todo" ${done==='todo'?'selected':''}>尚未完成</option><option value="done" ${done==='done'?'selected':''}>已完成</option></select><label class="inline"><input type="checkbox" name="hidden" value="1" ${hidden?'checked':''}>顯示隱藏成就（含劇透）</label><button class="primary">搜尋</button></form><div id="advance-results"></div>${notice(`本機資源共 ${advancements.length} 個顯示成就；${summary.technicalAdvancementCount.toLocaleString()} 個內部進度另存，不計完成率。父節點表示顯示關係，並非所有成就都強制要求先完成父節點。`)}`;
 const lower=needle.toLocaleLowerCase();const rows=advancements.filter(x=>(hidden||!x.hidden)&&(!group||groupFor(x.id.split(':')[0])===group)&&(!lower||`${x.title} ${x.description} ${x.id} ${JSON.stringify(x.criteria)}`.toLocaleLowerCase().includes(lower))&&(done==='done'?finished('advancement:'+x.id):done==='todo'?!finished('advancement:'+x.id):true));
 renderPage(rows,'advance-results',x=>`<div class="card atlas-state-card">${atlasStateButtons('advancement:'+x.id)}<a class="row" href="#advance/${enc(x.id)}">${image(x.icon?.item)}<div><span class="tag">${h(groupFor(x.id.split(':')[0]))}${x.hidden?' · 隱藏':''}</span><h3>${h(x.title)}</h3></div></a><p>${h(x.description)}</p><small>${x.requirements.length} 組條件${x.frame==='challenge'?' · 挑戰':''}</small></div>`);if(!rows.length&&done==='done')$('#advance-results').innerHTML=empty('目前沒有已取得的成就。完成成就後點卡片右上角的 ✓，就會顯示在這裡。');
 $('#advance-filter').onsubmit=e=>{e.preventDefault();pageNumber=1;go('collections?category=advancements&'+new URLSearchParams([...new FormData(e.target)]).toString())};
}
function advance(id){const x=advancements.find(x=>x.id===id);if(!x){app.innerHTML=empty('找不到成就');return}
 const key='advancement:'+id,chain=[];let p=x.parent;const seen=new Set([id]);while(p&&!seen.has(p)){seen.add(p);const parent=advancements.find(x=>x.id===p);if(!parent)break;chain.unshift(parent);p=parent.parent}
 const relatedItems=new Set();function scan(v){if(typeof v==='string'&&icons[v])relatedItems.add(v);else if(Array.isArray(v))v.forEach(scan);else if(v&&typeof v==='object')Object.values(v).forEach(scan)}scan(x.criteria);if(x.icon?.item)relatedItems.add(x.icon.item);
 const checklist=progress.get(key)?.checklist||{};
 app.innerHTML=atlasNav('advancements')+atlasBreadcrumb([{label:'成就',href:'#collections?category=advancements'}, {label:x.title}])+`<article class="article"><span class="tag gold">${h(groupFor(id.split(':')[0]))} ${x.hidden?'· 隱藏成就':''}</span><h1>${h(x.title)}</h1><p class="article-intro">${h(x.description)}</p>${x.missingParent?notice('本機資源沒有這個成就指定的前置節點；以下保留實際達成條件，未補造前置成就。',true):''}${chain.length?`<section class="panel"><h3>前置路線</h3>${chain.map(p=>`<a href="#advance/${enc(p.id)}">${h(p.title)}</a>`).join(' → ')} → <b>${h(x.title)}</b><p class="muted">這是遊戲顯示的父節點鏈；實際達成判定以本成就條件為準。</p></section>`:''}<h2>如何完成</h2><p class="muted">每組內任一條件成立即可，全部 ${x.requirements.length} 組都要成立。勾選條件只是個人紀錄。</p>${x.requirements.map((g,i)=>`<section class="condition-group"><b>第 ${i+1} 組${g.length>1?' · 選一項':''}</b>${g.map(k=>{const c=x.criteria.find(c=>c.key===k);return `<label class="inline"><input type="checkbox" data-criterion="${h(k)}" data-record="${h(key)}" ${checklist[k]?'checked':''}><span>${h(c?.instruction||k)}</span></label>`}).join('')}</section>`).join('')}${x.customTrigger?notice('這項成就含模組自訂或程式觸發條件。已查核成就資源中的判定，但尚未在遊戲內逐項驗證；若只顯示一般說明，請搭配成就描述與相關教學操作。',true):''}${relatedItems.size?`<section class="panel"><h3>相關物品與收藏</h3><div class="item-list">${[...relatedItems].slice(0,30).map(id=>{const c=collections.find(c=>c.id===id);return c?`<a class="item-link" href="#record/${enc(c.key)}">${image(id)}${h(c.title)}</a>`:`<button class="item-link" data-recipe="${h(id)}">${image(id)}${h(nameOf(id))}</button>`}).join('')}</div></section>`:''}${wishlistToggle(key,'想完成這個成就')}${completion(key,'我已在遊戲內取得此成就')}${notesPanel(key)}<div class="actions"><a class="btn" href="#journey/${enc(groupFor(id.split(':')[0])==='夥伴'?'探索':groupFor(id.split(':')[0])==='原版'?'起步':groupFor(id.split(':')[0]))}">相關領域教學</a><a class="btn" href="#collections?category=advancements">返回成就冊</a></div><details><summary>查核資訊</summary><p>${h(x.source.archive)}<br>${h(x.source.path)}</p><p>${h(x.status)}</p>${x.conditions?.length?`<p>資源另含啟用條件：${h(JSON.stringify(x.conditions))}</p>`:''}</details></article>`;
}
function globalSearch(query){const lower=query.trim().toLocaleLowerCase();app.innerHTML=heading('全站搜尋',query?`搜尋「${query}」`:'查找教學、物品、技能、首領與成就。')+`<form class="filters" id="global-filter"><input name="q" aria-label="全站搜尋" value="${h(query)}" placeholder="輸入關鍵字…"><button class="primary">搜尋</button></form><div id="search-results"></div>`;const rows=[];if(lower){for(const a of articles)if(`${a.title} ${a.intro} ${a.steps.join(' ')}`.toLocaleLowerCase().includes(lower))rows.push({title:a.title,text:a.intro,path:'article/'+a.id,category:'玩家教學'});for(const c of collections)if(`${c.title} ${c.subtitle} ${c.id} ${c.description}`.toLocaleLowerCase().includes(lower))rows.push({title:c.title,text:String(c.description).slice(0,140),path:'record/'+enc(c.key),category:CATEGORIES[c.category]});for(const a of advancements)if(!a.hidden&&`${a.title} ${a.description} ${JSON.stringify(a.criteria)}`.toLocaleLowerCase().includes(lower))rows.push({title:a.title,text:a.description,path:'advance/'+enc(a.id),category:'成就'});}renderPage(rows,'search-results',x=>`<a class="card card-link" href="#${x.path}"><span class="tag">${h(x.category)}</span><h3>${h(x.title)}</h3><p>${h(x.text)}</p></a>`);$('#global-filter').onsubmit=e=>{e.preventDefault();pageNumber=1;go('search?q='+enc(new FormData(e.target).get('q')))}}
function me(){
 if(cloudUnavailable){app.innerHTML=heading('雲端紀錄暫時無法連線','攻略仍可閱讀，稍後恢復連線再保存你的紀錄。')+`<button data-refresh-account>重試雲端連線</button>`;return}
 if(!user){openAuth();return}
 if(!active){app.innerHTML=heading('帳號待審批','請等待管理員核准。你仍可自由閱讀所有公開攻略。')+`<button data-refresh-account>重新檢查審批</button><button data-logout>登出</button>`;return}
 const all=[...collections.filter(x=>x.collectible),...advancements.map(x=>({...x,key:'advancement:'+x.id,category:'advancements'}))];
 app.innerHTML=heading(profile?.game_id||'我的紀錄','鐵血餘燼：王國飛翼・AOI 世界紀錄')+`<section class="panel profile-avatar-panel"><button data-avatar-edit aria-label="編輯我的頭像">${avatarImage(profile,cfg,h)}</button><button data-avatar-edit>編輯頭像</button></section><section class="panel"><h2>我的收藏進度</h2>${Object.entries(CATEGORIES).map(([k,v])=>{const rows=all.filter(x=>x.category===k),done=rows.filter(x=>finished(x.key)).length;return `<p><a href="#${'collections?category='+k}">${v} →</a></p>${bar(done,rows.length)}`}).join('')}</section><section class="panel"><h2>操作設定</h2><a class="btn" href="#keys">重新查看按鍵設定</a></section><section class="panel"><h2>隱私與顯示</h2><label class="complete-check"><input type="checkbox" id="share-progress" ${profile?.share_progress?'checked':''}>讓同隊查看我的收藏完成進度</label><label class="complete-check"><input type="checkbox" id="reduce-motion" ${document.documentElement.dataset.motion==='off'?'checked':''}>減少像素轉場與動畫</label><button data-export>下載我的紀錄備份</button></section><section class="panel"><h2>最近保存的紀錄</h2>${[...progress.values()].filter(x=>x.record_key&&!x.record_key.startsWith('guide:')&&!x.record_key.startsWith('settings:')).sort((a,b)=>b.updated_at.localeCompare(a.updated_at)).slice(0,15).map(x=>{const r=recordByKey().get(x.record_key);return `<p><a href="#${x.record_key.startsWith('advancement:')?'advance/'+enc(x.record_key.slice(12)):x.record_key.startsWith('article:')?'article/'+x.record_key.slice(8):'record/'+enc(x.record_key)}">${h(r?.title||articles.find(a=>'article:'+a.id===x.record_key)?.title||x.record_key)}</a>　${x.completed?'✓':''}</p>`}).join('')||'<p class="muted">還沒有紀錄。</p>'}</section><div class="actions"><button data-logout>登出</button>${isAdmin?'<a class="btn" href="#admin">管理員控制台</a>':''}</div><section class="panel"><h2>網站反饋</h2><a class="btn" href="#feedback">我的反饋</a></section>`;
}
async function saveRecord(key,patch){if(!needAccount())return false;const match={user_id:user.id,world_id:world.id,record_key:key},updated_at=new Date().toISOString();let rows=check(await db.from('progress').update({...patch,updated_at}).match(match).select());if(!rows.length){const r=await db.from('progress').insert({...match,...patch,updated_at}).select();if(r.error?.code==='23505')rows=check(await db.from('progress').update({...patch,updated_at}).match(match).select());else rows=check(r);}progress.set(key,rows[0]);return true}
function openAuth(mode='login'){if(authBusy)return;go('auth?mode='+enc(mode))}
function authPage(mode='login'){
 if(user){go('me');return}
 mode=['login','register','recover'].includes(mode)?mode:'login';
 const title=mode==='register'?'建立冒險者帳號':mode==='recover'?'使用復原碼重設密碼':'登入我的手札';
 const body=`<div class="chips auth-tabs" role="group" aria-label="帳號操作"><button data-auth-mode="login" aria-pressed="${mode==='login'}">登入</button><button data-auth-mode="register" aria-pressed="${mode==='register'}">註冊</button><button data-auth-mode="recover" aria-pressed="${mode==='recover'}">復原帳號</button></div><form id="auth-form" class="form-grid"><input type="hidden" name="action" value="${mode}"><label>遊戲 ID<input name="gameId" autocomplete="username" minlength="3" maxlength="32" required placeholder="你的玩家名稱"></label><label>${mode==='recover'?'新的網站密碼':'網站專用密碼'}<input name="password" type="password" autocomplete="${mode==='login'?'current-password':'new-password'}" minlength="10" maxlength="72" required placeholder="至少 10 個字元"></label>${mode==='recover'?'<label>復原碼<input name="recoveryCode" required autocomplete="off" placeholder="註冊保存的復原碼，或管理員提供的新碼"></label>':''}<p class="muted">新帳號需管理員核准。請使用網站專用密碼，勿使用 Minecraft／Microsoft 帳號密碼。</p><button class="primary" type="submit">${mode==='register'?'建立帳號並送審':mode==='recover'?'重設並登入':'登入'}</button><p id="auth-error" role="alert" class="warning-label"></p></form>`;
 app.innerHTML=`<section class="entry-page"><div class="entry-scene" aria-hidden="true"></div><div class="auth-card"><img class="auth-crown" src="assets/art/b026e708ac2763f03a2cb707.png" alt="" width="48" height="48"><h1>${h(title)}</h1>${body}<a class="auth-browse" href="#home" data-browse-entry>先瀏覽攻略 →</a><button id="auth-theme-toggle" class="auth-theme" aria-label="切換深色與淺色">☼</button></div></section>`;
 $('#auth-form').onsubmit=async e=>{e.preventDefault();if(authBusy)return;authBusy=true;const b=e.target.querySelector('button[type=submit]');b.disabled=true;try{const body=Object.fromEntries(new FormData(e.target));const r=await fetch(cfg.supabaseUrl+'/functions/v1/player-auth',{method:'POST',headers:{'Content-Type':'application/json','x-public-key':cfg.supabaseKey,apikey:cfg.supabaseKey},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'無法登入');check(await db.auth.setSession({access_token:data.session.access_token,refresh_token:data.session.refresh_token}));await loadAccount();if(data.recoveryCode){modal('請保存你的復原碼',`<p>此碼不會再次顯示。重設密碼後會換成新碼，舊碼失效。</p><p class="secret" id="recovery-secret">${h(data.recoveryCode)}</p><button data-copy-secret>複製復原碼</button><button data-close-secret>已保存</button>${notice(data.approved?'帳號已啟用。':'帳號已送審，請等待管理員核准。')}`)}else{closeModal();toast(data.approved?'歡迎回到你的世界':'帳號待管理員核准')}go('me');await render();}catch(e){if($('#auth-error'))$('#auth-error').textContent=e.message;else showError(e)}finally{authBusy=false;b.disabled=false}};
}
async function loadAccount(){const session=check(await db.auth.getSession()).session;user=session?.user||null;active=false;isAdmin=false;profile=null;world=null;progress.clear();teams=[];teamId='';if(channel){await db.removeChannel(channel);channel=null}
 if(!user){cloudUnavailable=false;updateAccountLabel();return}
 const status=check(await db.rpc('player_status'));cloudUnavailable=false;active=status.active;isAdmin=status.admin;if(active){profile=check(await db.from('profiles').select('*').eq('id',user.id).single());await resolveAvatars([profile],db);world=check(await db.from('worlds').select('*').eq('user_id',user.id).order('created_at').limit(1).single());for(let i=0;;i+=1000){const rows=check(await db.from('progress').select('*').eq('world_id',world.id).range(i,i+999));rows.forEach(x=>progress.set(x.record_key,x));if(rows.length<1000)break}await loadTeams();}updateAccountLabel();
}
function updateAccountLabel(){const b=$('#account-open');b.innerHTML=profile?avatarImage(profile,cfg,h):h(user?'待審批':'登入');b.setAttribute('aria-label',profile?'我的頁面：'+profile.game_id:'登入');if(profile)b.dataset.itemHint=profile.game_id;else delete b.dataset.itemHint;document.querySelectorAll('[data-nav="me"] .nav-icon').forEach(e=>e.innerHTML=profile?avatarImage(profile,cfg,h):navIcon('me'))}
async function loadTeams(){teams=check(await db.from('teams').select('*').order('created_at'));const remembered=localStorage.getItem('iaa-team-'+user.id);teamId=teams.some(x=>x.id===remembered)?remembered:teams[0]?.id||'';if(teamId)await subscribeTeam()}
async function subscribeTeam(){if(channel)await db.removeChannel(channel);if(!teamId)return;localStorage.setItem('iaa-team-'+user.id,teamId);channel=db.channel('team-'+teamId).on('postgres_changes',{event:'*',schema:'public',table:'requests',filter:'team_id=eq.'+teamId},p=>{if(p.table!=='requests')return;if(p.new?.author_id!==user.id)toast(p.eventType==='INSERT'?'隊伍有新的需求或邀約':'隊伍申請狀態已更新');if(route().path[0]==='team')refreshTeamOrdersQuietly().catch(showError)}).on('postgres_changes',{event:'INSERT',schema:'public',table:'request_comments'},p=>{if(p.table!=='request_comments')return;if(p.new?.author_id!==user.id)toast('隊伍申請有新留言');if(route().path[0]==='team')refreshTeamOrdersQuietly().catch(showError)}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'teams',filter:'id=eq.'+teamId},()=>{if(route().path[0]==='team')refreshTeamState().then(()=>{const id=$('#modal').dataset.requestId;if(id&&!requests.some(r=>r.id===id))closeModal()}).catch(showError)}).on('postgres_changes',{event:'*',schema:'public',table:'team_records',filter:'team_id=eq.'+teamId},()=>{if(route().path[0]==='team')refreshTeamOrdersQuietly().catch(showError)}).on('postgres_changes',{event:'INSERT',schema:'public',table:'request_notifications',filter:'user_id=eq.'+user.id},p=>{if(p.new?.team_id!==teamId)return;toast(p.new?.message||'你的訂單狀態有更新');const bell=document.querySelector('.team-notification-bell');if(bell){bell.classList.add('has-unread');if(!bell.querySelector('i'))bell.insertAdjacentHTML('beforeend','<i aria-hidden="true"></i>')}if(route().path[0]==='team'&&route().q.get('tab')==='notifications')refreshTeamOrdersQuietly().catch(showError)}).subscribe(status=>{if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')toast('即時連線暫時中斷；可按重新整理查看最新狀態',true)})}
function canManageTeam(){return isAdmin||teamMembers.some(m=>m.user_id===user?.id&&m.role==='admin')}
async function refreshTeamState(){teams=check(await db.from('teams').select('*').order('created_at'));if(!teams.some(t=>t.id===teamId)){await loadTeams();closeModal()}await render()}
async function team(){
 if(!active){app.innerHTML=heading('我的隊伍')+empty('請先登入已核准的帳號。')+`<button data-auth class="primary">登入／註冊</button>`;return}
 const tab=route().q.get('tab')||'requests';teamMembers=teamId?check(await db.from('team_members').select('user_id,role').eq('team_id',teamId)):[];
 const ids=teamMembers.map(m=>m.user_id),profiles=ids.length?check(await db.from('profiles').select('*').in('id',ids)):[];await resolveAvatars(profiles,db);players=new Map(profiles.map(p=>[p.id,p]));
 const selected=teams.find(t=>t.id===teamId),member=teamMembers.some(m=>m.user_id===user.id);
 let unreadNotifications=0;
 if(teamId)try{unreadNotifications=check(await db.from('request_notifications').select('id').eq('team_id',teamId).eq('user_id',user.id).is('read_at',null).limit(1000)).length}catch{}
 const teamHeading=`<div class="team-heading"><h1>我的隊伍</h1>${teamId?`<a class="team-notification-bell ${unreadNotifications?'has-unread':''}" href="#team?tab=notifications" aria-label="訂單通知${unreadNotifications?'，有 '+unreadNotifications+' 則未讀通知':''}" title="訂單通知"><span aria-hidden="true">🔔</span>${unreadNotifications?'<i aria-hidden="true"></i>':''}</a>`:''}</div>`;
 app.innerHTML=teamHeading+`<div class="team-switcher"><select id="team-select" aria-label="切換隊伍">${teams.length?teams.map(t=>`<option value="${t.id}" ${t.id===teamId?'selected':''}>${h(t.name)}</option>`).join(''):'<option value="">尚未加入隊伍</option>'}</select><button data-team-add aria-label="加入或建立隊伍">＋</button>${member?'<button data-team-leave>退出</button>':''}${teamId&&canManageTeam()?'<button data-team-manage>管理</button>':selected?.share_invite?'<button data-team-invite>邀請碼</button>':''}</div>${teamId?`<nav class="team-tabs" aria-label="隊伍分頁">${[['requests','需求與邀約'],['compare','隊員收藏比較'],['records','據點與里程碑'],['members','隊伍成員']].map(([id,label])=>`<a class="btn ${tab===id?'active':''}" href="#team?tab=${id}" ${tab===id?'aria-current="page"':''}>${label}</a>`).join('')}</nav><div id="team-content" class="loading">正在讀取隊伍…</div>`:empty('使用＋加入或建立隊伍。')}`;
 if(!teamId)return;
 if(tab==='compare'||tab==='progress')await compareTeam();else if(tab==='notifications')await notificationsTeam();else if(tab==='records')await recordsTeam();else if(tab==='members')membersTeam(profiles);else await requestsTeam();
}
function addTeam(){modal('加入或建立隊伍','<div class="actions"><button data-team-join>輸入邀請碼</button><button data-team-create>建立隊伍</button></div>')}
function leaveTeam(){const t=teams.find(t=>t.id===teamId);modal('退出隊伍',`<p>確認退出「${h(t?.name)}」？</p><div class="actions"><button id="team-leave-confirm" class="primary">確認退出</button><button data-close-secret>取消</button></div>`);$('#team-leave-confirm').onclick=async e=>{e.target.disabled=true;try{check(await db.rpc('leave_team',{t:teamId}));await loadTeams();closeModal();await render();toast('已退出隊伍')}catch(e){showError(e);$('#team-leave-confirm')?.removeAttribute('disabled')}}}
async function teamManagement(){
 if(!canManageTeam())throw Error('需要隊伍管理員權限');const t=teams.find(t=>t.id===teamId);
 modal('隊伍管理',`<div class="form-grid"><label class="inline"><input id="team-share-invite" type="checkbox" ${t?.share_invite?'checked':''}>每位隊員都可查看邀請碼</label><div class="actions"><button data-team-invite>查看邀請碼</button><button data-team-invite-renew>更新邀請碼</button></div><div class="team-member-list">${teamMembers.map(m=>`<section class="team-member-row"><div><b>${h(playerName(m.user_id))}</b><small>${m.role==='admin'?'隊伍管理員':'隊員'}</small></div><div class="actions"><button data-team-role="${m.user_id}" data-role="${m.role==='admin'?'member':'admin'}">${m.role==='admin'?'移除管理權':'設為管理員'}</button>${m.user_id!==user.id?`<button data-team-remove="${m.user_id}">移出隊伍</button>`:''}</div></section>`).join('')}</div></div>`);
 $('#team-share-invite').onchange=async e=>{const value=e.target.checked;try{check(await db.rpc('manage_team',{t:teamId,action:'share_invite',value:String(value)}));if(t)t.share_invite=value;toast('邀請碼權限已更新')}catch(err){e.target.checked=!value;showError(err)}};
}
async function teamInvite(renew=false){const code=check(await db.rpc('team_invite',{t:teamId,renew}));modal('隊伍邀請碼',code?`<p class="secret" id="recovery-secret">${h(code)}</p><p>有效七天，最多 20 次加入。</p><button data-copy-secret>複製邀請碼</button>`:empty('目前沒有可用的邀請碼，請聯絡隊伍管理員。'))}
async function requestsTeam(){
 const rows=check(await db.from('requests').select('*').eq('team_id',teamId).order('created_at',{ascending:false}).limit(200)).filter(r=>r.status!=='cancelled'||r.author_id===user.id);
 requests=rows.sort((a,b)=>Number(a.status==='cancelled')-Number(b.status==='cancelled')||new Date(b.created_at)-new Date(a.created_at));$('#team-content').className='';$('#team-content').innerHTML=`<div class="actions"><button class="primary" data-request-new>＋ 發布需求／邀約</button><button data-team-refresh>重新整理</button></div><div class="request-board">${requests.map(r=>requestCard(r)).join('')}</div>${requests.length?'':empty('隊伍目前沒有申請。可以先發布一張材料需求或遠征邀約。')}`}
async function refreshTeamOrdersQuietly(){
 if(route().path[0]!=='team'||!teamId)return;
 const tab=route().q.get('tab')||'requests';
 if(tab==='requests')await requestsTeam();
 else if(tab==='notifications')await notificationsTeam();
 const dialog=$('#modal'),rid=dialog?.dataset.requestId;
 if(rid&&dialog?.open)await comments(rid);
}
const statusNames={open:'等待接單',claimed:'進行中',submitted:'待發布者確認',completed:'已完成',cancelled:'已取消'};
function playerName(id){return players.get(id)?.game_id||'隊員'}
function requestActions(r){let a='';if(r.status==='open'&&r.author_id!==user.id)a+=`<button data-request-action="claim" data-rid="${r.id}">接單</button>`;if(r.status==='claimed'&&r.assignee_id===user.id)a+=`<button data-request-action="submit" data-rid="${r.id}">提交完成</button><button data-request-action="release" data-rid="${r.id}">釋出接單</button>`;if(r.status==='submitted'&&r.author_id===user.id)a+=`<button class="primary" data-request-action="complete" data-rid="${r.id}">確認完成</button><button data-request-action="reopen" data-rid="${r.id}">退回</button>`;if(['open','claimed','submitted'].includes(r.status)&&r.author_id===user.id)a+=`<button data-request-action="cancel" data-rid="${r.id}">取消</button>`;if(r.status==='cancelled'&&r.author_id===user.id)a+=`<button class="primary" data-request-action="restore" data-rid="${r.id}">恢復</button>`;return a}
function rewardDisplay(r){return r.reward_item_id&&r.reward_quantity?`<span class="reward-stack" data-item-hint="${h(names[r.reward_item_id]||r.reward_item_id)}" aria-label="${h(names[r.reward_item_id]||r.reward_item_id)}">${image(r.reward_item_id)}<b>× ${r.reward_quantity}</b></span>`:h(r.reward||'')}
function requestCard(r){if(r.status==='cancelled'&&r.author_id!==user.id)return '';const itemName=r.kind==='item'?(names[r.item_id]||r.title):'';return `<article class="board-note ${r.reward?'bounty-note':''} ${r.status==='cancelled'?'cancelled-note':''}"><span class="note-pin" aria-hidden="true"></span><button class="board-note-open" data-comments="${r.id}" aria-label="查看${h(r.title)}"><span class="note-status">${r.reward?'懸賞 · ':''}${statusNames[r.status]}</span>${r.kind==='item'?`<span class="note-item" data-item-hint="${h(itemName)}" aria-label="${h(itemName)}">${image(r.item_id||'minecraft:chest')}<b>× ${r.quantity||1}</b></span><span class="note-title">${h(itemName)}</span>`:`<strong class="note-title">${h(r.title)}</strong>`}${r.reward?`<span class="note-reward">報酬 · ${rewardDisplay(r)}</span>`:''}<small>${h(playerName(r.author_id))}${r.assignee_id?' → '+h(playerName(r.assignee_id)):''}</small></button>${r.status==='open'&&r.author_id!==user.id?`<button class="request-claim" data-request-action="claim" data-rid="${r.id}">接單</button>`:''}</article>`}
function newRequest(id){
 const old=id?requests.find(r=>r.id===id):null;if(old&&(old.author_id!==user.id||old.status!=='open'))throw Error('只有發布者能編輯尚未被接單的需求');
 modal(old?'編輯需求／懸賞':'發布留言板',`<form id="request-form" class="form-grid"><label>類型<select name="kind"><option value="item" ${old?.kind==='item'?'selected':''}>物品申請</option><option value="mission" ${old?.kind==='mission'?'selected':''}>任務邀約</option></select></label><div id="request-item-fields"><div class="item-quantity-row"><label>申請物品<input id="request-item" list="request-items" autocomplete="off" placeholder="搜尋物品"></label><label>數量<input name="quantity" type="number" min="1" max="1000000" value="${old?.quantity||1}" required></label></div><datalist id="request-items"></datalist><div id="request-item-preview" class="item-preview"></div></div><label>標題（最多 32 字）<input name="title" maxlength="32" required value="${h(old?.title||'')}"></label><label>內容<textarea name="body" maxlength="4000">${h(old?.body||'')}</textarea></label><label class="inline"><input id="request-paid" type="checkbox" ${old?.reward_item_id?'checked':''}>提供懸賞報酬</label><div id="reward-field" ${old?.reward_item_id?'':'hidden'}><div class="item-quantity-row"><label>獎勵物品<input id="reward-item" list="reward-items" autocomplete="off" placeholder="搜尋物品" ${old?.reward_item_id?'':'disabled'}></label><label>數量<input id="reward-quantity" name="reward_quantity" type="number" min="1" max="1000000" value="${old?.reward_quantity||1}" ${old?.reward_item_id?'':'disabled'}></label></div><datalist id="reward-items"></datalist><div id="reward-item-preview" class="item-preview"></div></div><label>交付／集合地點<input name="location" maxlength="200" value="${h(old?.location||'')}"></label><label>預定時間（UTC+8）<input name="scheduled_at" type="datetime-local" value="${old?.scheduled_at?h(new Date(old.scheduled_at).toLocaleString('sv-SE',{timeZone:'Asia/Singapore'}).slice(0,16)):''}"></label><button class="primary">${old?'儲存修改':'張貼'}</button></form>`);
 const ids=Object.keys(requestItems).filter(id=>icons[id]),lookup=new Map(ids.map(id=>[`${names[id]} · ${id}`,id]));let chosen=old?.item_id||'',reward=old?.reward_item_id||'';
 function displayValue(id){return id&&names[id]?`${names[id]} · ${id}`:id||''}
 function picker(inputId,listId,previewId,onChoose,initial=''){const input=$('#'+inputId);input.value=displayValue(initial);const update=()=>{const q=input.value.trim(),id=lookup.get(q)||(ids.includes(q)?q:'');onChoose(id);const matches=ids.filter(id=>id.includes(q)||names[id].includes(q)).slice(0,40);$('#'+listId).innerHTML=matches.map(id=>`<option value="${h(names[id])} · ${h(id)}"></option>`).join('');$('#'+previewId).innerHTML=id?image(id)+`<span data-item-hint="${h(names[id])}" aria-label="${h(names[id])}">${h(names[id])}</span>`:''};input.oninput=update;update()}
 picker('request-item','request-items','request-item-preview',id=>{chosen=id;if(id&&!$('#request-form input[name=title]').value)$('#request-form input[name=title]').value=names[id].slice(0,32)},old?.item_id||'');picker('reward-item','reward-items','reward-item-preview',id=>reward=id,old?.reward_item_id||'');
 const syncKind=()=>{const item=$('#request-form select[name=kind]').value==='item';$('#request-item-fields').hidden=!item;$('#request-item').disabled=!item;$('#request-form input[name=quantity]').disabled=!item;$('#request-form input[name=quantity]').required=item};$('#request-form select[name=kind]').onchange=syncKind;syncKind();
 $('#request-paid').onchange=e=>{const paid=e.target.checked;$('#reward-field').hidden=!paid;for(const i of $('#reward-field').querySelectorAll('input')){i.disabled=!paid;i.required=paid}};
 $('#request-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button.primary');b.disabled=true;try{const d=Object.fromEntries(new FormData(e.target)),paid=$('#request-paid').checked;if(d.kind==='item'&&!chosen)throw Error('請從申請物品清單選擇一項');if(paid&&!reward)throw Error('請從獎勵物品清單選擇一項');const payload={kind:d.kind,title:d.title.trim(),body:d.body||'',item_id:d.kind==='item'?chosen:'',reward:paid?names[reward]+' × '+d.reward_quantity:'',reward_item_id:paid?reward:null,reward_quantity:paid?Number(d.reward_quantity):null,quantity:d.kind==='item'?Number(d.quantity):null,location:d.location||'',scheduled_at:d.scheduled_at?new Date(d.scheduled_at+':00+08:00').toISOString():null,updated_at:new Date().toISOString()};if(old)check(await db.from('requests').update(payload).eq('id',old.id));else check(await db.from('requests').insert({...payload,team_id:teamId,author_id:user.id}));closeModal();toast(old?'已更新需求／懸賞':'已張貼到隊伍留言板');await refreshTeamOrdersQuietly()}catch(e){showError(e)}finally{b.disabled=false}}
}
async function comments(id){let r=requests.find(x=>x.id===id);if(!r){try{r=check(await db.from('requests').select('*').eq('id',id).single());if(r)requests.push(r)}catch{return}}if(!r||r.status==='cancelled'&&r.author_id!==user.id)return;const rows=check(await db.from('request_comments').select('*').eq('request_id',id).order('created_at'));const assignee=r.assignee_id?`<p><b>接單者：</b>${h(playerName(r.assignee_id))}</p>`:`<p class="muted">目前尚未有人接單。</p>`;const own=r.author_id===user.id;const ownerTools=(own&&r.status==='open'?'<button data-request-edit="'+r.id+'">編輯</button>':'')+(own&&['open','cancelled'].includes(r.status)?'<button data-request-delete="'+r.id+'">刪除</button>':'');modal(r.title,`<p class="detail-body">${h(r.body)}</p>${r.kind==='item'?`<div class="note-item" data-item-hint="${h(names[r.item_id]||r.title)}" aria-label="${h(names[r.item_id]||r.title)}">${image(r.item_id||'minecraft:chest')}<b>× ${r.quantity||1}</b></div>`:''}${r.reward?`<p class="reward-detail">報酬 · ${rewardDisplay(r)}</p>`:''}<p>${h(r.location)}</p>${r.scheduled_at?`<p>${h(new Date(r.scheduled_at).toLocaleString('zh-TW',{timeZone:'Asia/Singapore'}))}（UTC+8）</p>`:''}<p><b>發布者：</b>${h(playerName(r.author_id))} · ${statusNames[r.status]}</p>${assignee}<div class="actions">${requestActions(r)}${ownerTools}</div><div class="mini-list">${rows.map(c=>`<section class="panel"><small>${h(playerName(c.author_id))} · ${h(new Date(c.created_at).toLocaleString('zh-TW'))}</small><p class="detail-body">${h(c.body)}</p></section>`).join('')||'<p class="muted">還沒有留言。</p>'}</div><form id="comment-form" class="form-grid"><label>回覆<textarea name="body" required maxlength="2000"></textarea></label><button class="primary">送出留言</button></form>`);$('#modal').dataset.requestId=id;$('#comment-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{check(await db.from('request_comments').insert({request_id:id,author_id:user.id,body:new FormData(e.target).get('body')}));await comments(id)}catch(e){showError(e)}finally{b.disabled=false}}}
async function notificationsTeam(){
 let rows=[];
 try{rows=check(await db.from('request_notifications').select('*').eq('team_id',teamId).eq('user_id',user.id).order('created_at',{ascending:false}).limit(300))}catch(e){$('#team-content').className='';$('#team-content').innerHTML=notice('通知資料尚未啟用，請稍後重新整理。',true);return}
 $('#team-content').className='';
 $('#team-content').innerHTML=`<div class="notification-head"><h2>訂單通知</h2><button data-team-refresh>重新整理</button></div><div class="request-notifications">${rows.map(n=>`<article class="request-notification ${n.read_at?'':'unread'}"><div><strong>${h(n.title)}</strong><p>${h(n.message)}</p><small>${h(new Date(n.created_at).toLocaleString('zh-TW',{timeZone:'Asia/Singapore'}))}（UTC+8）</small></div>${n.request_id?`<button data-comments="${n.request_id}">查看訂單</button>`:''}</article>`).join('')||empty('目前沒有訂單通知。')}</div>`;
 const unread=rows.filter(n=>!n.read_at).map(n=>n.id);
 if(unread.length)try{check(await db.from('request_notifications').update({read_at:new Date().toISOString()}).in('id',unread));const bell=document.querySelector('.team-notification-bell');bell?.classList.remove('has-unread');bell?.querySelector('i')?.remove()}catch{}
}
async function compareTeam(){teamRows=[];for(let i=0;;i+=1000){const rows=check(await db.rpc('team_progress',{t:teamId}).order('user_id').order('record_key').range(i,i+999));teamRows.push(...rows);if(rows.length<1000)break}const shared=new Map();teamMembers.forEach(m=>{const p=players.get(m.user_id);shared.set(m.user_id,{id:m.user_id,profile:p,name:p?.game_id||'隊員',sharing:p?.share_progress===true,done:new Set()})});teamRows.forEach(r=>{const p=shared.get(r.user_id);if(p&&r.completed)p.done.add(r.record_key)});const all=[...collections.filter(x=>x.collectible),...advancements.map(x=>({key:'advancement:'+x.id,title:x.title,category:'advancements'}))];const cats=Object.entries(CATEGORIES),members=[...shared.values()],groups=[...cats.slice(0,4),['mounts','坐騎'],...cats.slice(4)];const rowsFor=k=>all.filter(x=>k==='mounts'?x.category==='companions'&&x.mount:x.category===k);
 $('#team-content').className='';$('#team-content').innerHTML=`<h2>收藏競賽</h2><div class="collection-races">${groups.map(([k,v],index)=>{const rows=rowsFor(k),entrants=members.map(p=>({...p,count:rows.filter(x=>p.done.has(x.key)).length})).sort((a,b)=>Number(b.sharing)-Number(a.sharing)||b.count-a.count||a.name.localeCompare(b.name));return `<details class="race-category" ${index===0?'open':''}><summary>${h(v)}</summary><div class="race-lanes">${entrants.map((p,i)=>`<div class="race-lane ${!p.sharing?'race-private':''}"><span class="race-rank">${p.sharing?i+1:'—'}</span><div class="race-course"><div class="race-road"><i style="width:${p.sharing?percent(p.count,rows.length):0}%"></i></div><button class="race-runner" style="left:${p.sharing?percent(p.count,rows.length):0}%" data-item-hint="${h(p.name)}${p.sharing?' · '+p.count+' / '+rows.length:' · 未分享'}" aria-label="${h(p.name)}：${p.sharing?percent(p.count,rows.length)+'%':'未分享'}">${avatarImage(p.profile,cfg,h)}</button></div><span class="race-score">${p.sharing?percent(p.count,rows.length)+'%':'未分享'}</span></div>`).join('')}</div></details>`}).join('')}</div><section class="panel"><h3>逐項比較</h3><form id="compare-filter" class="collection-search"><input name="q" aria-label="搜尋比較項目" placeholder="搜尋收藏名稱…"><details class="filter-drawer"><summary>篩選</summary><div class="filter-options"><select name="category" aria-label="比較收藏類型">${groups.map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><button>套用</button></div></details></form><div id="compare-table"></div></section>`;
 let comparePage=1;function draw(cat,needle=''){const rows=rowsFor(cat).filter(x=>x.title.toLowerCase().includes(needle.toLowerCase()));$('#compare-table').innerHTML=`<p class="muted">${rows.length} 筆 · 第 ${comparePage} / ${Math.max(1,Math.ceil(rows.length/60))} 頁</p><div class="comparison-scroll"><table class="item-matrix"><thead><tr><th>收藏項目</th>${members.map(p=>`<th title="${h(p.name)}">${h(p.name)}</th>`).join('')}</tr></thead><tbody>${rows.slice((comparePage-1)*60,comparePage*60).map(x=>`<tr><th><a href="#${x.category==='advancements'?'advance/'+enc(x.key.slice(12)):'record/'+enc(x.key)}">${h(x.title)}</a></th>${members.map(p=>`<td class="${p.sharing&&p.done.has(x.key)?'checkmark':''}" data-player="${h(p.name)}" aria-label="${h(p.name)}：${!p.sharing?'未分享':p.done.has(x.key)?'已完成':'未完成'}">${!p.sharing?'·':p.done.has(x.key)?'✓':'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="pager"><button id="compare-prev" ${comparePage===1?'disabled':''}>← 上頁</button><button id="compare-next" ${comparePage*60>=rows.length?'disabled':''}>下頁 →</button></div>`;$('#compare-prev').onclick=()=>{comparePage--;draw(cat,needle)};$('#compare-next').onclick=()=>{comparePage++;draw(cat,needle)}}draw('equipment');$('#compare-filter').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);comparePage=1;draw(d.get('category'),d.get('q'))};}
async function recordsTeam(){teamRecords=check(await db.from('team_records').select('*').eq('team_id',teamId).order('updated_at',{ascending:false}).limit(200));$('#team-content').className='';$('#team-content').innerHTML=`<button class="primary" data-record-new>＋ 新增據點／計畫／里程碑</button><div class="grid" style="margin-top:18px">${teamRecords.map(r=>`<section class="card"><span class="tag">${{base:'共享據點',plan:'建設計畫',milestone:'世界里程碑'}[r.kind]}</span><h3>${h(r.title)}</h3><p class="detail-body">${h(r.body)}</p><small>${h(playerName(r.author_id))}</small>${r.author_id===user.id||canManageTeam()?`<button data-record-edit="${r.id}">編輯</button>`:''}</section>`).join('')}</div>`}
function newTeamRecord(id){const old=teamRecords.find(x=>x.id===id);modal(old?'編輯共享紀錄':'新增共享紀錄',`<form id="team-record-form" class="form-grid"><label>類型<select name="kind" ${old?'disabled':''}>${[['base','共享據點'],['plan','建設計畫'],['milestone','世界里程碑']].map(([k,v])=>`<option value="${k}" ${old?.kind===k?'selected':''}>${v}</option>`).join('')}</select></label><label>標題<input name="title" required maxlength="160" value="${h(old?.title||'')}"></label><label>內容<textarea name="body" maxlength="8000" placeholder="維度、XYZ、建設分工、注意事項…">${h(old?.body||'')}</textarea></label><button class="primary">保存</button></form>`);$('#team-record-form').onsubmit=async e=>{e.preventDefault();try{const d=Object.fromEntries(new FormData(e.target));if(old)check(await db.from('team_records').update({title:d.title,body:d.body,updated_at:new Date().toISOString()}).eq('id',id));else check(await db.from('team_records').insert({...d,team_id:teamId,author_id:user.id}));closeModal();await render()}catch(e){showError(e)}}}
function membersTeam(rows){$('#team-content').className='';$('#team-content').innerHTML=`<h2>隊伍成員</h2><div class="grid">${rows.map(p=>`<div class="card"><h3>${h(p.game_id)}</h3><small>${teamMembers.find(m=>m.user_id===p.id)?.role==='admin'?'隊伍管理員':'隊員'} · ${p.share_progress?'分享收藏完成進度':'已關閉進度分享'}</small></div>`).join('')}</div>`}
async function adminPage(){if(!isAdmin){app.innerHTML=empty('需要管理員權限');return}const rows=check(await db.rpc('admin_players'));app.innerHTML=heading('管理員控制台','審批新玩家，或協助重設網站帳號。')+`<section class="panel"><h2>網站反饋</h2><a class="btn" href="#feedback?all=1">檢視全部反饋</a></section><section class="panel"><h2>伺服器隊伍管理</h2><div class="actions">${teams.map(t=>`<button data-admin-team="${t.id}">${h(t.name)}</button>`).join('')}</div></section><div class="grid">${rows.map(p=>`<section class="card"><span class="tag">${p.is_admin?'管理員':p.approved?'已核准':'待審批'}</span><h3>${h(p.game_id)}</h3><div class="actions">${!p.is_admin?`<button data-approve="${p.user_id}" data-allow="${!p.approved}">${p.approved?'停用帳號':'核准加入'}</button><button data-promote="${p.user_id}">設為管理員</button>`:''}<button data-admin-reset="${h(p.game_id)}">重設帳號密碼</button></div></section>`).join('')}</div>${notice('管理員重設會讓既有登入失效，產生一次性的復原碼。請自行確認玩家身分，再將復原碼私下交給本人。')}`}
function guide(slug){const atlas=ATLASES.find(a=>a[4]===slug);if(!atlas){app.innerHTML=empty('找不到攻略');return}const q=route().q;mountAtlas(atlas,{item:q.get('item'),query:q.get('q')||'',mode:q.get('view')||'all'})}
function normalizeCollectionFilter(){const form=$('#advance-filter');if(!form)return;form.className='collection-search';const input=form.querySelector('input[name=q]'),d=document.createElement('details'),summary=document.createElement('summary'),box=document.createElement('div');d.className='filter-drawer';summary.textContent='篩選';box.className='filter-options';for(const child of [...form.children])if(child!==input)box.append(child);d.append(summary,box);form.append(d)}
function installFilterDoneButtons(root=document){
 for(const d of root.querySelectorAll('.filter-drawer')){
  const box=d.querySelector('.filter-options,.filters,.pet-controls');if(!box||box.querySelector('.filter-done'))continue;
  const done=document.createElement('button');done.type='button';done.className='filter-done';done.textContent='完成';done.onclick=()=>d.removeAttribute('open');
  const reset=[...box.querySelectorAll('button')].find(b=>/清除|重設/.test(b.textContent)),row=document.createElement('div');row.className='filter-action-row';
  if(reset){reset.before(row);row.append(reset,done)}else{row.append(done);box.append(row)}
 }
}
async function render(){const sequence=++routeSequence,{path,q}=route();NAV.forEach(([id])=>{document.querySelectorAll(`[data-nav="${id}"]`).forEach(e=>e.classList.toggle('active',(path[0]===id||(id==='collections'&&['record','guide','advance','advancements'].includes(path[0])))))});app.classList.remove('route-enter');document.body.classList.remove('atlas-open');document.body.classList.toggle('entry-open',path[0]==='auth');document.body.classList.toggle('full-guide',path[0]==='guide'&&q.get('full')==='1');currentGuide=null;
 if(path[0]==='me'&&active&&needsKeySetup()){keyReturn='me';history.replaceState(null,'','#keys?onboard=1');return render()}
 try{switch(path[0]){case'keys':keysPage();break;case'auth':authPage(q.get('mode')||'login');break;case'home':home();break;case'journey':journey(path[1]);break;case'article':article(path[1]);break;case'collections':catalog();break;case'record':record(path.slice(1).join('/'));break;case'advancements':go('collections?category=advancements&'+q.toString());return;case'advance':advance(path.slice(1).join('/'));break;case'search':globalSearch(q.get('q')||'');break;case'me':me();break;case'team':await team();break;case'admin':await adminPage();break;case'feedback':await feedbackPage();break;case'guide':guide(path[1]);break;default:home()}if(sequence!==routeSequence)return;inventoryControls(app);normalizeCollectionFilter();installFilterDoneButtons(app);if(path[0]!=='team')app.classList.add('route-enter');}catch(e){app.innerHTML=notice('無法讀取資料：'+e.message,true)+`<button data-refresh-page>再試一次</button>`;showError(e)}
}
document.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;try{
 if(b.dataset.wishlistOpen){const key=b.dataset.wishlistOpen;if(key.startsWith('advancement:'))advancementModal(key.slice('advancement:'.length));else collectionModal(key)}
 else if(b.id==='modal-close')closeModal();else if(b.id==='theme-toggle'||b.id==='auth-theme-toggle'){document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('iaa-theme',document.documentElement.dataset.theme);$('#guide-frame')?.contentWindow.postMessage({type:'guide-theme',theme:document.documentElement.dataset.theme,motion:document.documentElement.dataset.motion},location.origin)}else if(b.id==='account-open'){if(user)go('me');else openAuth()}else if(b.id==='search-open'){modal('搜尋世界手札',`<form id="quick-search" class="form-grid"><input name="q" aria-label="搜尋關鍵字" placeholder="名稱、配方、技能、首領…" autofocus required><button class="primary">搜尋</button></form>`);$('#quick-search').onsubmit=e=>{e.preventDefault();const q=new FormData(e.target).get('q');closeModal();pageNumber=1;go('search?q='+enc(q))}}
 else if(b.hasAttribute('data-browse-entry')){e.preventDefault();keyReturn=initialHash&&!/^#(?:auth|me|admin|team|keys)(?:[/?]|$)/.test(initialHash)?initialHash.slice(1):'home';go(needsKeySetup()?'keys?onboard=1':keyReturn)}else if(b.hasAttribute('data-auth'))openAuth();else if(b.dataset.authMode)openAuth(b.dataset.authMode);else if(b.dataset.materialTag)materialOptions(b.dataset.materialTag);else if(b.dataset.recipe)itemRecipe(b.dataset.recipe);else if(b.dataset.page){pageNumber=Number(b.dataset.page);await render();window.scrollTo(0,80)}
 else if(b.dataset.bossReference){e.preventDefault();await bossModal(b.dataset.bossReference)}else if(b.hasAttribute('data-avatar-edit'))editAvatar();else if(b.hasAttribute('data-feedback-new'))newFeedback();else if(b.dataset.feedbackOpen)await openFeedback(b.dataset.feedbackOpen);else if(b.dataset.atlasNote){if(needAccount())modal('我的私人筆記',notesPanel(b.dataset.atlasNote))}
 else if(b.hasAttribute('data-refresh-account')){await loadAccount();await render()}
 else if(b.hasAttribute('data-logout')){check(await db.auth.signOut());await loadAccount();await render()}
 else if(b.hasAttribute('data-export')){const blob=new Blob([JSON.stringify({gameId:profile.game_id,exportedAt:new Date().toISOString(),progress:[...progress.values()]},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='AOI-我的紀錄.json';a.click();URL.revokeObjectURL(url)}
 else if(b.hasAttribute('data-copy-secret')){await navigator.clipboard.writeText($('#recovery-secret').textContent);toast('已複製，請保存到私人位置')}
 else if(b.hasAttribute('data-close-secret'))closeModal();
 else if(b.hasAttribute('data-team-add'))addTeam();else if(b.hasAttribute('data-team-leave'))leaveTeam();else if(b.hasAttribute('data-team-manage'))await teamManagement();else if(b.hasAttribute('data-team-invite')||b.hasAttribute('data-team-invite-renew'))await teamInvite(b.hasAttribute('data-team-invite-renew'));else if(b.dataset.teamRole){check(await db.rpc('manage_team',{t:teamId,action:'role',uid:b.dataset.teamRole,value:b.dataset.role}));await refreshTeamState();if(canManageTeam())await teamManagement();else closeModal()}else if(b.dataset.teamRemove){const uid=b.dataset.teamRemove;modal('移出隊伍',`<p>確認將 ${h(playerName(uid))} 移出隊伍？</p><button id="team-remove-confirm" class="primary">確認移出</button>`);$('#team-remove-confirm').onclick=async()=>{try{check(await db.rpc('manage_team',{t:teamId,action:'remove',uid}));await refreshTeamState();await teamManagement()}catch(err){showError(err)}}}
 else if(b.hasAttribute('data-team-create')||b.hasAttribute('data-team-join')){const join=b.hasAttribute('data-team-join');modal(join?'加入隊伍':'建立隊伍',`<form id="team-action-form" class="form-grid"><label>${join?'邀請碼':'隊伍名稱'}<input name="value" required maxlength="${join?32:80}"></label><button class="primary">${join?'加入':'建立'}</button></form>`);$('#team-action-form').onsubmit=async e=>{e.preventDefault();try{const value=new FormData(e.target).get('value');const t=check(await db.rpc(join?'join_team':'create_team',join?{c:value}:{n:value}));localStorage.setItem('iaa-team-'+user.id,t);await loadTeams();closeModal();await render()}catch(e){showError(e)}}}
 else if(b.hasAttribute('data-invite')){const code=check(await db.rpc('create_invite',{t:teamId}));modal('隊伍邀請碼',`<p>有效七天，最多 20 次加入。請只分享給隊友。</p><p class="secret" id="recovery-secret">${h(code)}</p><button data-copy-secret>複製邀請碼</button>`)}
 else if(b.hasAttribute('data-request-new'))newRequest();else if(b.dataset.requestEdit){newRequest(b.dataset.requestEdit)}else if(b.dataset.requestDelete){const rid=b.dataset.requestDelete,r=requests.find(x=>x.id===rid);modal('刪除需求／懸賞',`<p>確定永久刪除「${h(r?.title||'這則需求')}」？留言也會一起刪除。</p><div class="actions"><button id="request-delete-confirm" class="primary">確認刪除</button><button data-close-secret>取消</button></div>`);$('#request-delete-confirm').onclick=async()=>{try{check(await db.from('requests').delete().eq('id',rid));closeModal();toast('已刪除');await refreshTeamOrdersQuietly()}catch(e){showError(e)}}}else if(b.dataset.requestAction==='cancel'){const rid=b.dataset.rid,r=requests.find(x=>x.id===rid);modal('取消需求／懸賞',`<p>確定取消「${h(r?.title||'這則需求')}」？取消後不會再顯示給其他隊員，但你仍可在自己的列表中恢復。</p><div class="actions"><button id="request-cancel-confirm" class="primary">確認取消</button><button data-close-secret>返回</button></div>`);$('#request-cancel-confirm').onclick=async()=>{const c=$('#request-cancel-confirm');c.disabled=true;try{check(await db.rpc('request_action',{rid,action:'cancel'}));closeModal();toast('已取消；需要時可從自己的列表恢復');await refreshTeamOrdersQuietly()}catch(e){showError(e);c.disabled=false}}}
 else if(b.dataset.requestAction){b.disabled=true;check(await db.rpc('request_action',{rid:b.dataset.rid,action:b.dataset.requestAction}));toast(b.dataset.requestAction==='restore'?'已恢復並重新公開':'申請狀態已更新');const rid=b.dataset.rid;await refreshTeamOrdersQuietly();if($('#modal').open)await comments(rid)}
 else if(b.dataset.comments)await comments(b.dataset.comments);else if(b.hasAttribute('data-record-new'))newTeamRecord();else if(b.dataset.recordEdit)newTeamRecord(b.dataset.recordEdit);else if(b.hasAttribute('data-team-refresh')||b.hasAttribute('data-refresh-page'))await render();
 else if(b.dataset.adminTeam){teamId=b.dataset.adminTeam;await subscribeTeam();go('team')}else if(b.dataset.approve){check(await db.rpc('admin_approve',{uid:b.dataset.approve,allow:b.dataset.allow==='true'}));await render()}
 else if(b.dataset.promote){const uid=b.dataset.promote;modal('授予網站管理權限','<p>此玩家將能核准其他帳號與協助重設密碼。</p><button class="primary" id="promote-confirm">確認授予</button>');$('#promote-confirm').onclick=async()=>{try{check(await db.rpc('admin_make',{uid}));closeModal();await render()}catch(e){showError(e)}}}
 else if(b.dataset.adminReset){const gameId=b.dataset.adminReset;modal('協助重設帳號',`<p>將使 ${h(gameId)} 的既有登入失效並產生新的復原碼。請先確認玩家身分。</p><button id="admin-reset-confirm" class="primary">產生一次性復原碼</button>`);$('#admin-reset-confirm').onclick=async()=>{try{const session=check(await db.auth.getSession()).session;const r=await fetch(cfg.supabaseUrl+'/functions/v1/player-auth',{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg.supabaseKey,'x-public-key':cfg.supabaseKey,Authorization:'Bearer '+session.access_token},body:JSON.stringify({action:'admin-reset',gameId,password:'admin-operation-placeholder'})});const data=await r.json();if(!r.ok)throw Error(data.error);modal('新的復原碼',`<p>請私下交給 ${h(gameId)}。對方在「復原帳號」設定自己的新密碼。</p><p class="secret" id="recovery-secret">${h(data.recoveryCode)}</p><button data-copy-secret>複製</button>`)}catch(e){showError(e)}}}
 }catch(e){showError(e);if(b.tagName==='BUTTON')b.disabled=false}});
document.addEventListener('change',async e=>{const x=e.target;try{if(x.dataset.wish){const checked=x.checked;if(!needAccount()){x.checked=!checked;return}x.disabled=true;try{const checklist={...(progress.get(x.dataset.wish)?.checklist||{}),wish:checked};await saveRecord(x.dataset.wish,{checklist});toast(checked?'已加入我想收集':'已從我想收集移除')}catch(e){x.checked=!checked;throw e}finally{x.disabled=false}}
 else if(x.dataset.complete){const checked=x.checked;if(!needAccount()){x.checked=!checked;return}x.disabled=true;try{await saveRecord(x.dataset.complete,{completed:checked});toast('收藏進度已保存')}catch(e){x.checked=!checked;throw e}finally{x.disabled=false}}
 else if(x.dataset.criterion){if(!needAccount()){x.checked=!x.checked;return}const key=x.dataset.record,checklist={...(progress.get(key)?.checklist||{}),[x.dataset.criterion]:x.checked};await saveRecord(key,{checklist})}
 else if(x.id==='share-progress'){if(!needAccount())return;check(await db.from('profiles').update({share_progress:x.checked}).eq('id',user.id));profile.share_progress=x.checked;toast(x.checked?'已開啟同隊進度分享':'已關閉同隊進度分享')}
 else if(x.id==='reduce-motion'){document.documentElement.dataset.motion=x.checked?'off':'on';localStorage.setItem('iaa-motion',x.checked?'off':'on')}
 else if(x.id==='team-select'){teamId=x.value;await subscribeTeam();await render()}}catch(e){showError(e)}});
document.addEventListener('submit',async e=>{if(!e.target.dataset.note)return;e.preventDefault();if(!needAccount())return;const b=e.target.querySelector('button');b.disabled=true;try{await saveRecord(e.target.dataset.note,{notes:new FormData(e.target).get('notes')});toast('私人筆記已保存')}catch(e){showError(e)}finally{b.disabled=false}});
window.addEventListener('message',e=>{const popup=$('#atlas-modal-frame'),isPopup=e.source===popup?.contentWindow,iframe=isPopup?popup:$('#guide-frame'),context=isPopup?popupContext:currentGuide;if(e.origin!==location.origin||e.source!==iframe?.contentWindow||!context)return;const d=e.data;if(d?.slug!==context.slug)return;if(d.type==='atlas-mode-route'&&!isPopup){const next=route().q;next.set('category',context.category);next.delete('done');if(d.mode&&d.mode!=='all')next.set('view',d.mode);else next.delete('view');go('collections?'+next.toString());return;}if(d.type==='boss-reference'){bossModal(d.id).catch(showError);return;}if(d.type==='reader-ready'){iframe.dataset.ready='true';iframe.setAttribute('aria-busy','false');if(!isPopup)document.querySelector('.reader-loading-indicator')?.remove()}if(d.type==='guide-item'&&icons[d.id])itemRecipe(d.id);if(d.type==='guide-ready'){iframe.contentWindow.postMessage({type:'atlas-open',id:context.item,query:context.query,reference:context.reference,done:context.done,mode:context.mode||'all',view:context.category==='companions'?'pets':context.category==='mounts'?'mounts':'boss',wishes:collections.filter(c=>c.sourceGuide===context.slug&&wanted(c.key)).map(c=>c.id)},location.origin);setTimeout(()=>{if(iframe.dataset.ready==='true'||!iframe.isConnected)return;try{delete iframe.contentDocument.documentElement.dataset.readerLoading}catch{}iframe.setAttribute('aria-busy','false');if(!isPopup)document.querySelector('.reader-loading-indicator')?.remove()},2500)}if(d.type==='atlas-wish'){const c=collections.find(c=>c.sourceGuide===context.slug&&c.id===d.id&&c.collectible);if(c&&active){const checklist={...(progress.get(c.key)?.checklist||{}),wish:!!d.wanted};saveRecord(c.key,{checklist}).catch(showError)}}if(d.type==='guide-progress'&&active&&d.data&&typeof d.data==='object'){clearTimeout(guideTimer);const slug=d.slug,data=d.data,uid=user.id;guideTimer=setTimeout(async()=>{if(!active||user?.id!==uid)return;try{const before=writeGuide(slug,progress.get('guide:'+slug)?.checklist||{},progress,collections),old=readGuide(slug,before),next=readGuide(slug,data),keys=new Set([...old.keys(),...next.keys()]);for(const key of keys){if(!collections.some(c=>c.key===key&&c.collectible))continue;const a=old.get(key)||{completed:false},b=next.get(key)||{completed:false},patch={};if(a.completed!==b.completed)patch.completed=b.completed;if('notes'in b&&a.notes!==b.notes)patch.notes=b.notes;if(a.wanted!==b.wanted)patch.checklist={...(progress.get(key)?.checklist||{}),wish:!!b.wanted};if(Object.keys(patch).length)await saveRecord(key,patch)}await saveRecord('guide:'+slug,{checklist:data});}catch(e){showError(e)}},500)}});
window.addEventListener('hashchange',()=>{if(booting)return;pageNumber=1;window.scrollTo(0,0);render().catch(showError)});
window.addEventListener('online',()=>{toast('已恢復網路連線');if(teamId)subscribeTeam().catch(showError)});
async function init(){try{cfg=await fetch('site-config.json').then(r=>r.json());document.title=cfg.siteTitle;[articles,collections,advancements,icons,summary,recipes,originals,names,materialTags,keyGuide,requestItems]=await Promise.all(['articles','collections','advancements','icons','summary','tutorial-recipes','originals','names','tutorial-item-tags','key-guide','request-items'].map(name=>fetch('data/'+name+'.json').then(r=>{if(!r.ok)throw Error('攻略資料載入失敗');return r.json()})));for(const [id,label]of Object.entries(requestItems))if(!names[id])names[id]=label;collections=collections.filter(x=>x.category!=='skills'||x.collectible);db=createClient(cfg.supabaseUrl,cfg.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true}});$('#desktop-nav').innerHTML=NAV.map(([id,icon,name])=>`<a data-nav="${id}" href="#${id}"><span class="nav-icon">${navIcon(id)}</span>${name}</a>`).join('');$('#mobile-nav').innerHTML=NAV.map(([id,icon,name])=>`<a data-nav="${id}" href="#${id}"><span class="nav-icon">${navIcon(id)}</span>${name}</a>`).join('');$('#intro-name').innerHTML=`<span class="intro-name-zh">${h(cfg.serverNameZh)}</span><span class="intro-name-en">${h(cfg.serverNameEn)}</span>`;$('#intro-status').textContent='正在確認冒險者身分…';try{await loadAccount()}catch(e){cloudUnavailable=true;active=false;toast('雲端紀錄暫時無法連線，攻略仍可閱讀。請稍後重試。',true)}history.replaceState(null,'','#'+(user?'me':initialHash.startsWith('#auth?')?initialHash.slice(1):'auth'));
 await render();await finishIntro();db.auth.onAuthStateChange((event,session)=>{if(event==='TOKEN_REFRESHED')user=session?.user||null;if(event==='SIGNED_OUT'&&user){user=null;active=false;progress.clear();if(channel){db.removeChannel(channel);channel=null}updateAccountLabel();render().catch(showError)}})}catch(e){app.innerHTML=notice('載入失敗，請確認網路後重新整理。'+e.message,true)+`<button id="reload-entry">重新開啟手札</button>`;$('#reload-entry').onclick=()=>location.reload();skipIntro=true;await finishIntro();}}
init();

let popupContext=null;
function advancementModal(id){
 const x=advancements.find(x=>x.id===id);if(!x)return;
 const key='advancement:'+id;
 const groups=x.requirements.map((g,i)=>`<section class="condition-group"><b>第 ${i+1} 組${g.length>1?' · 選一項':''}</b>${g.map(k=>{const q=x.criteria.find(c=>c.key===k);return `<div class="modal-condition">• ${h(q?.instruction||k)}</div>`}).join('')}</section>`).join('');
 modal(x.title,`<div class="atlas-modal-detail"><div class="modal-atlas-state">${atlasStateButtons(key)}</div><span class="tag">${h(groupFor(id.split(':')[0]))}${x.hidden?' · 隱藏成就':''}</span><p class="article-intro">${h(x.description)}</p><h3>如何完成</h3>${groups}${x.customTrigger?notice('這項成就包含模組自訂或程式觸發條件。'):''}</div>`);
}
function collectionModal(key){
 const x=collections.find(x=>x.key===key);if(!x)return;
 const modalCategory=x.mount?'mounts':x.category;
 const atlas=ATLASES.find(a=>a[0]===modalCategory)||ATLASES.find(a=>a[4]===x.sourceGuide);if(!atlas)return;
 const [category,,title,,slug]=atlas,g=originals.find(g=>g.id===slug);if(!g)return;
 const uid=user?.id||'guest',saved=progress.get('guide:'+slug)?.checklist||{},data=active?writeGuide(slug,saved,progress,collections):saved;
 for(const [k,v]of Object.entries(data))localStorage.setItem('iaa-guide-'+uid+'-'+slug+'-'+k,v);
 popupContext={slug,category,item:x.category==='strategy'?x.key.replace('scarlet:',''):x.id,query:x.title,reference:!x.collectible,mode:'all'};
 modal(x.title,`<iframe id="atlas-modal-frame" class="boss-modal-frame" title="${h(x.title)}" src="${g.path}?player=${enc(uid)}&atlas=${enc(slug)}&section=${enc(category)}&popup=1&reader=20261006-aoi19"></iframe>`);
 $('#modal').classList.add('boss-dialog');
 const modalFrame=$('#atlas-modal-frame');modalFrame?.addEventListener('load',()=>refreshAtlasReader(modalFrame),{once:true});
}
async function bossModal(id){
 const x=collections.find(x=>x.category==='bosses'&&x.id===id);if(x)collectionModal(x.key);
}
document.addEventListener('boss-reference',e=>bossModal(e.detail).catch(showError));
$('#modal').addEventListener('close',()=>{$('#modal').classList.remove('boss-dialog');$('#atlas-modal-frame')?.remove();popupContext=null});
const feedbackStatuses={not_started:'未開始',reviewed:'已審閱',in_progress:'進行中',completed:'已完成'};
let feedbackRows=[];
async function feedbackPage(){if(!needAccount())return;const all=isAdmin&&route().q.get('all')==='1';let query=db.from('feedback').select('*').order('created_at',{ascending:false});if(!all)query=query.eq('author_id',user.id);feedbackRows=[];for(let offset=0;;offset+=1000){const rows=check(await query.range(offset,offset+999));feedbackRows.push(...rows);if(rows.length<1000)break}
 app.innerHTML=heading(all?'網站反饋管理':'我的反饋')+`<div class="actions"><button class="primary" data-feedback-new>＋ 提交反饋</button>${isAdmin?`<a class="btn" href="#feedback${all?'':'?all=1'}">${all?'只看我的反饋':'查看全部反饋'}</a>`:''}<a class="btn" href="#me">返回我的頁面</a></div><form id="feedback-filter" class="collection-search"><input name="q" placeholder="搜尋反饋…" aria-label="搜尋反饋"><details class="filter-drawer"><summary>篩選</summary><div class="filter-options"><select name="status" aria-label="反饋狀態"><option value="">全部狀態</option>${Object.entries(feedbackStatuses).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><button>套用</button></div></details></form><div id="feedback-list"></div>`;
 const draw=()=>{const f=new FormData($('#feedback-filter')),rows=feedbackRows.filter(r=>(!f.get('status')||r.status===f.get('status'))&&(r.title+' '+r.body).toLowerCase().includes(String(f.get('q')||'').toLowerCase()));$('#feedback-list').innerHTML=rows.map(r=>`<button class="feedback-card" data-feedback-open="${r.id}"><span class="feedback-status feedback-${r.status}">${feedbackStatuses[r.status]}</span><h3>${h(r.title)}</h3><small>${r.kind==='idea'?'功能建議':'問題回報'} · ${h(new Date(r.created_at).toLocaleDateString('zh-TW'))}</small>${r.admin_reply?'<span class="reply-indicator">管理員已回覆</span>':''}</button>`).join('')||empty('目前沒有反饋。')};draw();$('#feedback-filter').onsubmit=e=>{e.preventDefault();draw();$('#feedback-filter details').open=false};
}
function newFeedback(){modal('提交網站反饋',`<form id="feedback-form" class="form-grid"><label>類型<select name="kind"><option value="issue">問題回報</option><option value="idea">功能建議</option></select></label><label>標題<input name="title" required maxlength="60"></label><label>內容<textarea name="body" required maxlength="4000" placeholder="遇到問題時，請描述在哪個頁面、如何操作，以及預期結果。"></textarea></label><button class="primary">提交</button></form>`);$('#feedback-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const d=Object.fromEntries(new FormData(e.target));check(await db.from('feedback').insert({...d,title:d.title.trim(),body:d.body.trim(),author_id:user.id}));closeModal();toast('反饋已送交網站管理員');await feedbackPage()}catch(e){showError(e)}finally{b.disabled=false}}}
async function openFeedback(id){const r=check(await db.from('feedback').select('*').eq('id',id).single());modal(r.title,`<span class="feedback-status feedback-${r.status}">${feedbackStatuses[r.status]}</span><p class="detail-body">${h(r.body)}</p>${r.admin_reply?`<section class="panel"><h3>管理員回覆</h3><p class="detail-body">${h(r.admin_reply)}</p></section>`:''}${isAdmin?`<form id="feedback-review" class="form-grid"><label>處理狀態<select name="status">${Object.entries(feedbackStatuses).map(([k,v])=>`<option value="${k}" ${r.status===k?'selected':''}>${v}</option>`).join('')}</select></label><label>回覆／處理結果<textarea name="reply" maxlength="4000">${h(r.admin_reply)}</textarea></label><button class="primary">保存處理狀態</button></form>`:''}`);if(isAdmin)$('#feedback-review').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const d=new FormData(e.target);check(await db.rpc('review_feedback',{f:id,s:d.get('status'),reply:d.get('reply')}));closeModal();toast('反饋狀態已更新');await feedbackPage()}catch(e){showError(e)}finally{b.disabled=false}}}

function editAvatar(){if(!needAccount())return;openAvatarEditor({profile,user,db,cfg,h,modal,check,onSaved:p=>{profile=p;updateAccountLabel();closeModal();toast("頭像已更新");render().catch(showError)},onError:showError})}
setInterval(async()=>{if(!active||document.visibilityState!=='visible')return;const rows=[profile,...players.values()].filter(Boolean);await resolveAvatars(rows,db);const byId=new Map(rows.map(p=>[p.id,p]));for(const image of document.querySelectorAll('img.player-avatar[data-avatar-user]')){const p=byId.get(image.dataset.avatarUser);if(p?.avatar_path&&p.avatar_url)image.src=p.avatar_url;}},240000);