import {tagName,stationName,heatName} from './recipe-labels.js';
import {createClient} from '@supabase/supabase-js';
import {readGuide,writeGuide} from './guide-progress.js';
const $=s=>document.querySelector(s),h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),enc=encodeURIComponent;
const CATEGORIES={equipment:'裝備',skills:'技能與法術',bosses:'首領與事件',companions:'夥伴與坐騎',strategy:'實戰攻略',advancements:'成就'};
const NAV=[['home','▥','世界'],['collections','⚒','圖鑑'],['advancements','✦','成就'],['team','⚑','隊伍'],['me','▣','我的']];
const GROUPS=[['起步','▣','熟悉世界','操作、地圖、補給與救援'],['定居','▥','建立家園','殖民地、居民、建設與防衛'],['生產','⚒','鋼鐵產業','動力、加工、倉儲與物流'],['旅行','↗','連結疆域','鐵路、船舶、跑酷與飛行'],['戰鬥','⚔','掌握秘法','武器、技能、法術與配裝'],['探索','♜','踏入未知','地牢、首領、夥伴與終界'],['協作','⚑','共建帝國','隊伍、需求與遠征邀約'],['收藏','✦','留下足跡','圖鑑、成就與完成進度']];
let cfg,db,articles,collections,advancements,icons,summary,recipes,originals,names;
let user=null,active=false,isAdmin=false,cloudUnavailable=false,profile=null,world=null,progress=new Map(),teams=[],teamId='',channel=null,teamRows=[],requests=[],teamRecords=[],players=new Map(),currentGuide=null,pageNumber=1;
let routeSequence=0,guideTimer,authBusy=false;
const app=$('#main');
function toast(message,error=false){const e=document.createElement('div');e.className='toast'+(error?' error':'');e.textContent=message;$('#toasts').append(e);setTimeout(()=>e.remove(),7000)}
function check(r){if(r.error)throw Error(r.error.message);return r.data}
function showError(e){toast(e.message||'暫時無法完成，請再試一次',true)}
function modal(title,body){$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;if(!$('#modal').open)$('#modal').showModal()}
function closeModal(){$('#modal').close()}
function route(){const hash=location.hash.slice(1)||'home',i=hash.indexOf('?');return {path:(i<0?hash:hash.slice(0,i)).split('/').map(decodeURIComponent),q:new URLSearchParams(i<0?'':hash.slice(i+1))}}
function go(path){location.hash=path}
const empty=text=>`<div class="empty">${h(text)}</div>`;
const notice=(text,warn=false)=>`<div class="notice${warn?' warn':''}">${h(text)}</div>`;
function percent(done,total){return total?Math.round(done/total*100):0}
function bar(done,total){return `<div class="progressbar"><span style="width:${percent(done,total)}%"></span></div><small>${done} / ${total} · ${percent(done,total)}%</small>`}
function image(id,cls=''){return icons[id]?`<img class="${cls}" src="${h(icons[id])}" alt="" loading="lazy" width="48" height="48">`:`<span class="card-icon" aria-hidden="true">${id?.includes('advancement')?'✦':'▣'}</span>`}
function heading(title,desc){return `<div class="page-heading"><p class="eyebrow">IRON & ARCANA · PLAYER GUIDE</p><h1>${h(title)}</h1><p>${h(desc)}</p></div>`}
function breadcrumb(title){return `<div class="breadcrumb"><a href="#home">世界</a> / ${h(title)}</div>`}
function finished(key){return !!progress.get(key)?.completed}
function completion(key,label='已完成收藏'){return `<label class="complete-check"><input type="checkbox" data-complete="${h(key)}" ${finished(key)?'checked':''}>${h(label)}</label>`}
function needAccount(){if(active&&user&&world)return true;toast(user?'帳號仍待管理員核准':'請登入已核准的帳號來保存紀錄');openAuth();return false}
function groupFor(ns){if(['minecolonies','supplementaries','webdisplaystogether'].includes(ns))return '定居';if(['create','ae2','vintage','tetra','butchercraft','create_enchantment_industry','createmetallurgy','create_connected','farmersdelight','kaleidoscope_cookery'].includes(ns))return '生產';if(['northstar','railways','createrailwaysnavigator'].includes(ns))return '旅行';if(['irons_spellbooks','efn','slu','bonfires','onekick'].includes(ns))return '戰鬥';if(['alexsmobs','adorablehamsterpets','saintsdragons','dragonsofberk'].includes(ns))return '夥伴';return ns==='minecraft'?'原版':'探索'}
const recordByKey=()=>new Map([...collections.map(x=>[x.key,x]),...advancements.map(x=>['advancement:'+x.id,{...x,key:'advancement:'+x.id,category:'advancements',collectible:true}])]);
function articleCard(a){const g=GROUPS.find(g=>g[0]===a.group);return `<a class="card card-link" href="#article/${enc(a.id)}"><span class="tag">${h(a.group)}</span><h3>${h(a.title)}</h3><p>${h(a.intro)}</p><small>${a.steps.length} 個操作步驟　<span style="color:var(--gold)">開啟手札 →</span></small></a>`}
function home(){
 const total=collections.filter(x=>x.collectible).length;
 app.innerHTML=`<section class="hero"><img class="hero-art" src="assets/world.svg" alt="像素城堡、森林與飛龍"><div class="hero-copy"><p class="eyebrow">YOUR NEXT ADVENTURE STARTS HERE</p><p class="server-en">${h(cfg.serverNameEn)}</p><h1>${h(cfg.serverNameZh)}</h1><p class="tagline">${h(cfg.taglineZh)}<small style="display:block;margin-top:7px">${h(cfg.taglineEn)}</small></p><p class="muted">${h(cfg.description)}</p><div class="actions"><a class="btn primary" href="#article/start">開始我的征途 →</a><a class="btn" href="#collections">打開收藏圖鑑</a></div></div></section>
 <div class="stats"><div class="stat"><b>${articles.length}</b><small>玩家教學</small></div><div class="stat"><b>${total.toLocaleString()}</b><small>收藏項目</small></div><div class="stat"><b>${advancements.length.toLocaleString()}</b><small>成就條目</small></div></div>
 <div class="section-head"><h2>今天，想完成什麼？</h2><small>從一個目標開始</small></div><div class="grid cols3">${GROUPS.map(g=>`<a href="#journey/${enc(g[0])}" class="card card-link"><div class="card-icon">${g[1]}</div><h3>${h(g[2])}</h3><p>${h(g[3])}</p><small>${articles.filter(a=>a.group===g[0]).length} 篇手札　→</small></a>`).join('')}</div>
 <div class="section-head"><h2>一條有脈絡的征途</h2><small>可自由選擇支線</small></div><div class="trail">${[['start','熟悉新世界','查配方、調按鍵、建立回程路線'],['land','找到家園','選址，留出殖民地與工廠空間'],['colony-start','讓聚落成長','先讓建築工、食物與物流運作'],['factory','讓鋼鐵流動','把材料加工接到基地供應'],['combat','掌握自己的力量','選武器、技能與法術，練習實際操作'],['expedition','把足跡留向遠方','地牢、首領、夥伴與成就']].map((p,i)=>`<a href="#article/${p[0]}"><span class="number">${i+1}</span><span><b>${h(p[1])}</b><small>${h(p[2])}</small></span></a>`).join('')}</div>
 <div class="section-head"><h2>你的冒險收藏冊</h2><a href="#collections">全部 →</a></div><div class="grid">${originals.map(x=>`<a class="card card-link" href="#guide/${x.id}"><h3>${h(x.title)}</h3><p>完整配方、圖片與操作說明</p><small>展開原攻略 →</small></a>`).join('')}</div>${notice('攻略依 2026-10-04 本機模組資源查核。伺服器可能調整配方、數值、生成與成就；網站紀錄由玩家手動填寫。')}`;
}
function journey(group){const g=GROUPS.find(x=>x[0]===group);app.innerHTML=breadcrumb(g?.[2]||group)+heading(g?.[2]||group,g?.[3]||'依玩家目標串起教學')+`<div class="grid">${articles.filter(a=>a.group===group).map(articleCard).join('')}</div>`}
function article(id){const a=articles.find(x=>x.id===id);if(!a){app.innerHTML=empty('找不到這篇手札');return}
 app.innerHTML=breadcrumb(a.group)+`<article class="article"><span class="tag gold">${h(a.group)}</span><h1>${h(a.title)}</h1><p class="article-intro">${h(a.intro)}</p>${a.items.length?`<section class="panel"><h3>先準備這些</h3><div class="item-list">${a.items.map(x=>`<button class="item-link" data-recipe="${h(x.id)}">${image(x.id)}${h(x.name)}</button>`).join('')}</div><small>點物品查看本機配方或取得說明。</small></section>`:''}<h2>照著操作</h2>${a.steps.map((s,i)=>`<div class="step"><span class="number">${i+1}</span><p>${h(s)}</p></div>`).join('')}<section class="panel"><h2>卡住時先看這裡</h2><ul>${a.troubleshooting.map(x=>`<li>${h(x)}</li>`).join('')}</ul></section><section><h2>下一步可以接到…</h2><div class="grid">${a.related.map(id=>articles.find(x=>x.id===id)).filter(Boolean).map(articleCard).join('')}</div></section>${completion('article:'+a.id,'我已實際完成這篇教學')}<details><summary>查核範圍與參考</summary><p class="muted">${h(a.evidence)}</p>${a.sources.map(s=>`<p><a href="${h(s)}" target="_blank" rel="noopener">官方功能說明 ↗</a></p>`).join('')}</details></article>`;
}
function itemRecipe(id){const d=recipes[id];let html='';if(d?.recipes?.length){html=d.recipes.map(r=>renderRecipe(r.raw)).join('')}else html=notice('沒有找到可直接展示的普通合成配方。此項目可能需要工作站、改造、召喚或其他取得方式；請以遊戲內配方與指南查詢。');modal(d?.name||nameOf(id),html)}
function nameOf(id){return recipes[id]?.name||names[id]||collections.find(x=>x.id===id)?.title||id}
function ingredient(v){if(!v)return '';if(typeof v==='string')return nameOf(v);if(Array.isArray(v))return v.map(ingredient).join(' 或 ');if(v.item)return nameOf(v.item)+(v.count?' × '+v.count:'');if(v.tag)return tagName(v.tag)+'（可用材料依遊戲配方選項）';if(v.fluid)return ({'minecraft:water':'水','minecraft:lava':'熔岩'}[v.fluid]||names[v.fluid]||'指定流體')+(v.amount?' '+v.amount+' mB':'');return '此工作站使用的特殊材料，請以遊戲內選項確認'}
function renderRecipe(r){
 let body='';if(r.pattern){body=`<table><tbody>${r.pattern.map(row=>`<tr>${[...row].map(k=>`<td>${k===' '?'空格':h(ingredient(r.key?.[k]))}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
 else if(r.ingredients)body=`<ul>${r.ingredients.map(x=>`<li>${h(ingredient(x))}</li>`).join('')}</ul>`;
 else if(r.ingredient)body=`<p>${h(ingredient(r.ingredient))}</p>`;
 if(r.sequence)body+=`<ol>${r.sequence.map(s=>`<li>${h(stationName(s.type))}：${h((s.ingredients||[]).map(ingredient).join('、'))}</li>`).join('')}</ol>`;
 const types={'minecraft:crafting_shaped':'合成台・依格位放置','minecraft:crafting_shapeless':'合成台・不限制格位','minecraft:smelting':'熔爐','minecraft:blasting':'高爐','minecraft:smoking':'煙燻爐','create:pressing':'機械壓製機','create:mixing':'機械攪拌器','create:sequenced_assembly':'序列組裝','create:mechanical_crafting':'機械合成器'};
 return `<section class="panel"><h3>${h(types[r.type]||'指定工作站配方')}</h3>${body}${r.heatRequirement?`<p>熱度：${h(heatName(r.heatRequirement))}</p>`:''}${r.loops?`<p>重複 ${r.loops} 次</p>`:''}<p>產物：${h(r.results?r.results.map(ingredient).join('、'):ingredient(r.result))}</p><small>本機配方資源；伺服器可能覆蓋。</small></section>`;
}
const ATLASES=[
 ['equipment','⚒','裝備收藏冊','依系列瀏覽、想收集清單、素材追查、完整配方與掉落來源','equipment'],
 ['skills','✦','技能與法術','功能、持握條件、取得方法、法術學派與參考清單','skills'],
 ['bosses','♜','首領與事件','出現地點、召喚方式、分段戰術、遇見／擊敗／獎勵進度','bosses'],
 ['companions','♥','夥伴','馴服條件、照顧方法、用途與準備進度','bosses'],
 ['mounts','↗','坐騎','坐騎比較、速度與乘騎條件、取得與馴服方法','bosses'],
 ['strategy','⚔','緋紅獵人實戰手冊','章節導覽、整套配裝、增益清單、機制圖解與實戰流程','scarlet']
];
function atlasNav(category,noteKey){return `<nav class="atlas-tabs" aria-label="圖鑑分類"><a href="#collections" ${!category?'aria-current="page"':''}>▥ 圖鑑首頁</a>${ATLASES.map(([id,icon,title])=>`<a href="#collections?category=${id}" ${id===category?'aria-current="page"':''}>${icon} ${title}</a>`).join('')}${noteKey?`<button class="atlas-note" data-atlas-note="${h(noteKey)}">私人筆記</button>`:''}</nav>`}
function catalog(){const {q}=route(),category=q.get('category')||'',query=q.get('q')||'';
 const atlas=ATLASES.find(a=>a[0]===category);
 if(atlas){mountAtlas(atlas,{query,done:q.get('done')||'all'});return}
 app.innerHTML=heading('冒險收藏圖鑑','選一本收藏冊，沿著完整說明、配方與取得途徑規劃下一場冒險。')+`<form id="atlas-search" class="filters"><input name="q" aria-label="搜尋全部圖鑑" placeholder="搜尋裝備、技能、首領或夥伴…" value="${h(query)}"><button class="primary">搜尋所有圖鑑</button></form><div class="grid cols3 atlas-shelves">${ATLASES.map(([id,icon,title,desc])=>{const rows=collections.filter(x=>x.category===(id==='mounts'?'companions':id)&&x.collectible);return `<a class="card card-link atlas-book" href="#collections?category=${id}"><span class="card-icon">${icon}</span><h2>${title}</h2><p>${desc}</p>${rows.length&&id!=='mounts'?`<small>已收藏 ${rows.filter(x=>finished(x.key)).length} / ${rows.length}</small>`:''}<span class="atlas-enter">打開收藏冊 →</span></a>`}).join('')}</div><section class="panel"><h2>一起完成收藏</h2><p>各收藏冊保留自己的分類、篩選、展開說明與備份功能。登入後，完成進度會同步到你的帳號；隊友可在隊伍頁比較收藏，私人筆記與想收集清單只有自己能查看。</p><div class="actions"><a class="btn" href="#team?tab=progress">隊伍收藏比較</a><a class="btn" href="#advancements">成就全收集</a></div></section>`;
 $('#atlas-search').onsubmit=e=>{e.preventDefault();go('search?q='+enc(new FormData(e.target).get('q')))};
}
function mountAtlas(atlas,options={}){
 const [category,,title,,slug]=atlas,g=originals.find(g=>g.id===slug);
 const saved=progress.get('guide:'+slug)?.checklist||{},data=active?writeGuide(slug,saved,progress,collections):saved,uid=user?.id||'guest';
 for(const [k,v] of Object.entries(data))localStorage.setItem('iaa-guide-'+uid+'-'+slug+'-'+k,v);
 currentGuide={slug,category,...options};
 document.body.classList.add('atlas-open');
 app.innerHTML=atlasNav(category,options.recordKey&&['skills','scarlet'].includes(slug)?options.recordKey:null)+`<iframe class="guide-frame atlas-frame" id="guide-frame" title="${h(title)}" src="${g.path}?player=${enc(uid)}&atlas=${slug}&reader=20261004-hints3" allow="clipboard-write"></iframe>`;
}
function renderPage(rows,target,render){const size=30,last=Math.max(1,Math.ceil(rows.length/size));pageNumber=Math.min(pageNumber,last);$('#'+target).innerHTML=`<p class="result-count">${rows.length.toLocaleString()} 筆 · 第 ${pageNumber} / ${last} 頁</p><div class="grid cols3">${rows.slice((pageNumber-1)*size,pageNumber*size).map(render).join('')}</div>${rows.length?`<div class="pager"><button data-page="${pageNumber-1}" ${pageNumber===1?'disabled':''}>← 上頁</button><span>${pageNumber} / ${last}</span><button data-page="${pageNumber+1}" ${pageNumber===last?'disabled':''}>下頁 →</button></div>`:empty('沒有符合條件的項目，試試不同關鍵字。')}`}
function record(key){const x=collections.find(x=>x.key===key);if(!x){app.innerHTML=empty('找不到收藏項目');return}
 const atlas=ATLASES.find(a=>a[0]===x.category)||ATLASES.find(a=>a[4]===x.sourceGuide);
 if(atlas)mountAtlas(atlas,{item:x.category==='strategy'?x.key.replace('scarlet:',''):x.id,query:x.title,reference:!x.collectible,title:x.title,recordKey:x.key});
 else app.innerHTML=empty('找不到這項收藏的攻略');
}
function notesPanel(key){return `<section class="panel"><h3>我的私人筆記</h3><form data-note="${h(key)}"><textarea aria-label="私人筆記" name="notes" maxlength="8000" placeholder="材料進度、嘗試結果、下一步…">${h(progress.get(key)?.notes||'')}</textarea><button class="primary">保存筆記</button><small>只有本人可讀取；隊伍比較只分享完成狀態。</small></form></section>`}
function advanceList(){const {q}=route(),needle=q.get('q')||'',group=q.get('group')||'',hidden=q.get('hidden')==='1',done=q.get('done')||'all';
 app.innerHTML=heading('成就全收集','查看前置鏈與達成條件，逐步留下你在這個世界的足跡。')+`<form id="advance-filter" class="filters"><input name="q" aria-label="搜尋成就" placeholder="搜尋名稱、物品或條件…" value="${h(needle)}"><select name="group" aria-label="成就領域"><option value="">所有領域</option>${['原版','定居','生產','旅行','戰鬥','探索','夥伴'].map(g=>`<option ${group===g?'selected':''}>${g}</option>`).join('')}</select><select name="done" aria-label="成就完成狀態"><option value="all">所有進度</option><option value="todo" ${done==='todo'?'selected':''}>尚未完成</option><option value="done" ${done==='done'?'selected':''}>已完成</option></select><label class="inline"><input type="checkbox" name="hidden" value="1" ${hidden?'checked':''}>顯示隱藏成就（含劇透）</label><button class="primary">搜尋</button></form><div id="advance-results"></div>${notice(`本機資源共 ${advancements.length} 個顯示成就；${summary.technicalAdvancementCount.toLocaleString()} 個內部進度另存，不計完成率。父節點表示顯示關係，並非所有成就都強制要求先完成父節點。`)}`;
 const lower=needle.toLocaleLowerCase();const rows=advancements.filter(x=>(hidden||!x.hidden)&&(!group||groupFor(x.id.split(':')[0])===group)&&(!lower||`${x.title} ${x.description} ${x.id} ${JSON.stringify(x.criteria)}`.toLocaleLowerCase().includes(lower))&&(done==='done'?finished('advancement:'+x.id):done==='todo'?!finished('advancement:'+x.id):true));
 renderPage(rows,'advance-results',x=>`<div class="card"><a class="row" href="#advance/${enc(x.id)}">${image(x.icon?.item)}<div><span class="tag">${h(groupFor(x.id.split(':')[0]))}${x.hidden?' · 隱藏':''}</span><h3>${h(x.title)}</h3></div></a><p>${h(x.description)}</p>${completion('advancement:'+x.id)}<small>${x.requirements.length} 組條件${x.frame==='challenge'?' · 挑戰':''}</small></div>`);
 $('#advance-filter').onsubmit=e=>{e.preventDefault();pageNumber=1;go('advancements?'+new URLSearchParams([...new FormData(e.target)]).toString())};
}
function advance(id){const x=advancements.find(x=>x.id===id);if(!x){app.innerHTML=empty('找不到成就');return}
 const key='advancement:'+id,chain=[];let p=x.parent;const seen=new Set([id]);while(p&&!seen.has(p)){seen.add(p);const parent=advancements.find(x=>x.id===p);if(!parent)break;chain.unshift(parent);p=parent.parent}
 const relatedItems=new Set();function scan(v){if(typeof v==='string'&&icons[v])relatedItems.add(v);else if(Array.isArray(v))v.forEach(scan);else if(v&&typeof v==='object')Object.values(v).forEach(scan)}scan(x.criteria);if(x.icon?.item)relatedItems.add(x.icon.item);
 const checklist=progress.get(key)?.checklist||{};
 app.innerHTML=breadcrumb('成就')+`<article class="article"><span class="tag gold">${h(groupFor(id.split(':')[0]))} ${x.hidden?'· 隱藏成就':''}</span><h1>${h(x.title)}</h1><p class="article-intro">${h(x.description)}</p>${x.missingParent?notice('本機資源沒有這個成就指定的前置節點；以下保留實際達成條件，未補造前置成就。',true):''}${chain.length?`<section class="panel"><h3>前置路線</h3>${chain.map(p=>`<a href="#advance/${enc(p.id)}">${h(p.title)}</a>`).join(' → ')} → <b>${h(x.title)}</b><p class="muted">這是遊戲顯示的父節點鏈；實際達成判定以本成就條件為準。</p></section>`:''}<h2>如何完成</h2><p class="muted">每組內任一條件成立即可，全部 ${x.requirements.length} 組都要成立。勾選條件只是個人紀錄。</p>${x.requirements.map((g,i)=>`<section class="condition-group"><b>第 ${i+1} 組${g.length>1?' · 選一項':''}</b>${g.map(k=>{const c=x.criteria.find(c=>c.key===k);return `<label class="inline"><input type="checkbox" data-criterion="${h(k)}" data-record="${h(key)}" ${checklist[k]?'checked':''}><span>${h(c?.instruction||k)}</span></label>`}).join('')}</section>`).join('')}${x.customTrigger?notice('這項成就含模組自訂或程式觸發條件。已查核成就資源中的判定，但尚未在遊戲內逐項驗證；若只顯示一般說明，請搭配成就描述與相關教學操作。',true):''}${relatedItems.size?`<section class="panel"><h3>相關物品與收藏</h3><div class="item-list">${[...relatedItems].slice(0,30).map(id=>{const c=collections.find(c=>c.id===id);return c?`<a class="item-link" href="#record/${enc(c.key)}">${image(id)}${h(c.title)}</a>`:`<button class="item-link" data-recipe="${h(id)}">${image(id)}${h(nameOf(id))}</button>`}).join('')}</div></section>`:''}${completion(key,'我已在遊戲內取得此成就')}${notesPanel(key)}<div class="actions"><a class="btn" href="#journey/${enc(groupFor(id.split(':')[0])==='夥伴'?'探索':groupFor(id.split(':')[0])==='原版'?'起步':groupFor(id.split(':')[0]))}">相關領域教學</a><a class="btn" href="#advancements">返回成就冊</a></div><details><summary>查核資訊</summary><p>${h(x.source.archive)}<br>${h(x.source.path)}</p><p>${h(x.status)}</p>${x.conditions?.length?`<p>資源另含啟用條件：${h(JSON.stringify(x.conditions))}</p>`:''}</details></article>`;
}
function globalSearch(query){const lower=query.trim().toLocaleLowerCase();app.innerHTML=heading('全站搜尋',query?`搜尋「${query}」`:'查找教學、物品、技能、首領與成就。')+`<form class="filters" id="global-filter"><input name="q" aria-label="全站搜尋" value="${h(query)}" placeholder="輸入關鍵字…"><button class="primary">搜尋</button></form><div id="search-results"></div>`;const rows=[];if(lower){for(const a of articles)if(`${a.title} ${a.intro} ${a.steps.join(' ')}`.toLocaleLowerCase().includes(lower))rows.push({title:a.title,text:a.intro,path:'article/'+a.id,category:'玩家教學'});for(const c of collections)if(`${c.title} ${c.subtitle} ${c.id} ${c.description}`.toLocaleLowerCase().includes(lower))rows.push({title:c.title,text:String(c.description).slice(0,140),path:'record/'+enc(c.key),category:CATEGORIES[c.category]});for(const a of advancements)if(!a.hidden&&`${a.title} ${a.description} ${JSON.stringify(a.criteria)}`.toLocaleLowerCase().includes(lower))rows.push({title:a.title,text:a.description,path:'advance/'+enc(a.id),category:'成就'});}renderPage(rows,'search-results',x=>`<a class="card card-link" href="#${x.path}"><span class="tag">${h(x.category)}</span><h3>${h(x.title)}</h3><p>${h(x.text)}</p></a>`);$('#global-filter').onsubmit=e=>{e.preventDefault();pageNumber=1;go('search?q='+enc(new FormData(e.target).get('q')))}}
function me(){
 if(cloudUnavailable){app.innerHTML=heading('雲端紀錄暫時無法連線','攻略仍可閱讀，稍後恢復連線再保存你的紀錄。')+`<button data-refresh-account>重試雲端連線</button>`;return}
 if(!user){app.innerHTML=heading('我的冒險紀錄','把收藏、成就與私人筆記保存到同一個世界。')+empty('登入已核准的帳號後，開始你的收藏紀錄。')+`<button class="primary" data-auth>登入／註冊</button>`;return}
 if(!active){app.innerHTML=heading('帳號待審批','請等待管理員核准。你仍可自由閱讀所有公開攻略。')+`<button data-refresh-account>重新檢查審批</button><button data-logout>登出</button>`;return}
 const all=[...collections.filter(x=>x.collectible),...advancements.map(x=>({...x,key:'advancement:'+x.id,category:'advancements'}))];
 app.innerHTML=heading(profile?.game_id||'我的紀錄','鋼鐵與秘法：帝國紀元・單一世界紀錄')+`<section class="panel"><h2>我的收藏進度</h2>${Object.entries(CATEGORIES).filter(([k])=>k!=='strategy').map(([k,v])=>{const rows=all.filter(x=>x.category===k),done=rows.filter(x=>finished(x.key)).length;return `<p><a href="#${k==='advancements'?'advancements':'collections?category='+k}">${v} →</a></p>${bar(done,rows.length)}`}).join('')}</section><section class="panel"><h2>隱私與顯示</h2><label class="complete-check"><input type="checkbox" id="share-progress" ${profile?.share_progress?'checked':''}>讓同隊查看我的收藏完成進度</label><p class="muted">只分享完成狀態。筆記與成就條件的細部勾選始終私人。</p><label class="complete-check"><input type="checkbox" id="reduce-motion" ${document.documentElement.dataset.motion==='off'?'checked':''}>減少像素轉場與動畫</label><button data-export>下載我的紀錄備份</button></section><section class="panel"><h2>最近保存的紀錄</h2>${[...progress.values()].filter(x=>x.record_key&&!x.record_key.startsWith('guide:')).sort((a,b)=>b.updated_at.localeCompare(a.updated_at)).slice(0,15).map(x=>{const r=recordByKey().get(x.record_key);return `<p><a href="#${x.record_key.startsWith('advancement:')?'advance/'+enc(x.record_key.slice(12)):x.record_key.startsWith('article:')?'article/'+x.record_key.slice(8):'record/'+enc(x.record_key)}">${h(r?.title||articles.find(a=>'article:'+a.id===x.record_key)?.title||x.record_key)}</a>　${x.completed?'✓':''}</p>`}).join('')||'<p class="muted">還沒有紀錄。</p>'}</section><div class="actions"><button data-logout>登出</button>${isAdmin?'<a class="btn" href="#admin">管理員控制台</a>':''}</div>`;
}
async function saveRecord(key,patch){if(!needAccount())return false;const match={user_id:user.id,world_id:world.id,record_key:key},updated_at=new Date().toISOString();let rows=check(await db.from('progress').update({...patch,updated_at}).match(match).select());if(!rows.length){const r=await db.from('progress').insert({...match,...patch,updated_at}).select();if(r.error?.code==='23505')rows=check(await db.from('progress').update({...patch,updated_at}).match(match).select());else rows=check(r);}progress.set(key,rows[0]);return true}
function openAuth(mode='login'){
 modal(mode==='register'?'建立冒險者帳號':mode==='recover'?'使用復原碼重設密碼':'登入我的手札',`<div class="chips"><button data-auth-mode="login">登入</button><button data-auth-mode="register">註冊</button><button data-auth-mode="recover">復原帳號</button></div><form id="auth-form" class="form-grid"><input type="hidden" name="action" value="${mode}"><label>遊戲 ID<input name="gameId" autocomplete="username" minlength="3" maxlength="32" required placeholder="你的玩家名稱"></label><label>${mode==='recover'?'新的網站密碼':'網站專用密碼'}<input name="password" type="password" autocomplete="${mode==='login'?'current-password':'new-password'}" minlength="10" maxlength="72" required placeholder="至少 10 個字元"></label>${mode==='recover'?'<label>復原碼<input name="recoveryCode" required autocomplete="off" placeholder="註冊保存的復原碼，或管理員提供的新碼"></label>':''}${mode==='register'?'<details><summary>我是首次管理員</summary><label>首次管理員啟用碼<input name="setupCode" autocomplete="off" placeholder="從本機啟用碼檔案取得"></label></details>':''}<p class="muted">不需要信箱。請勿使用 Minecraft／Microsoft 帳號密碼。ID 不驗證遊戲帳號本人，新帳號需管理員核准。</p><button class="primary" type="submit">${mode==='register'?'建立帳號並送審':mode==='recover'?'重設並登入':'登入'}</button><p id="auth-error" role="alert" class="warning-label"></p></form>`);
 $('#auth-form').onsubmit=async e=>{e.preventDefault();if(authBusy)return;authBusy=true;const b=e.target.querySelector('button[type=submit]');b.disabled=true;try{const body=Object.fromEntries(new FormData(e.target));const r=await fetch(cfg.supabaseUrl+'/functions/v1/player-auth',{method:'POST',headers:{'Content-Type':'application/json','x-public-key':cfg.supabaseKey,apikey:cfg.supabaseKey},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'無法登入');check(await db.auth.setSession({access_token:data.session.access_token,refresh_token:data.session.refresh_token}));await loadAccount();if(data.recoveryCode){modal('請保存你的復原碼',`<p>此碼不會再次顯示。重設密碼後會換成新碼，舊碼失效。</p><p class="secret" id="recovery-secret">${h(data.recoveryCode)}</p><button data-copy-secret>複製復原碼</button><button data-close-secret>已保存</button>${notice(data.approved?'帳號已啟用。':'帳號已送審，請等待管理員核准。')}`)}else{closeModal();toast(data.approved?'歡迎回到你的世界':'帳號待管理員核准')}go('me');await render();}catch(e){if($('#auth-error'))$('#auth-error').textContent=e.message;else showError(e)}finally{authBusy=false;b.disabled=false}};
}
async function loadAccount(){const session=check(await db.auth.getSession()).session;user=session?.user||null;active=false;isAdmin=false;profile=null;world=null;progress.clear();teams=[];teamId='';if(channel){await db.removeChannel(channel);channel=null}
 if(!user){updateAccountLabel();return}
 const status=check(await db.rpc('player_status'));cloudUnavailable=false;active=status.active;isAdmin=status.admin;if(active){profile=check(await db.from('profiles').select('*').eq('id',user.id).single());world=check(await db.from('worlds').select('*').eq('user_id',user.id).order('created_at').limit(1).single());for(let i=0;;i+=1000){const rows=check(await db.from('progress').select('*').eq('world_id',world.id).range(i,i+999));rows.forEach(x=>progress.set(x.record_key,x));if(rows.length<1000)break}await loadTeams();}updateAccountLabel();
}
function updateAccountLabel(){$('#account-open').textContent=profile?.game_id||(user?'待審批':'登入')}
async function loadTeams(){teams=check(await db.from('teams').select('*').order('created_at'));const remembered=localStorage.getItem('iaa-team-'+user.id);teamId=teams.some(x=>x.id===remembered)?remembered:teams[0]?.id||'';if(teamId)await subscribeTeam()}
async function subscribeTeam(){if(channel)await db.removeChannel(channel);if(!teamId)return;localStorage.setItem('iaa-team-'+user.id,teamId);channel=db.channel('team-'+teamId).on('postgres_changes',{event:'*',schema:'public',table:'requests',filter:'team_id=eq.'+teamId},p=>{if(p.new?.author_id!==user.id)toast(p.eventType==='INSERT'?'隊伍有新的需求或邀約':'隊伍申請狀態已更新');if(route().path[0]==='team')render().catch(showError)}).on('postgres_changes',{event:'INSERT',schema:'public',table:'request_comments'},p=>{if(p.new?.author_id!==user.id)toast('隊伍申請有新留言');if(route().path[0]==='team')render().catch(showError)}).on('postgres_changes',{event:'*',schema:'public',table:'team_records',filter:'team_id=eq.'+teamId},()=>{if(route().path[0]==='team')render().catch(showError)}).subscribe(status=>{if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')toast('即時連線暫時中斷；可按重新整理查看最新狀態',true)})}
async function team(){if(!active){app.innerHTML=heading('一起建立帝國','隊伍共享據點、收藏進度、物品需求與遠征邀約。')+empty('請登入已核准的帳號，再加入或建立隊伍。')+`<button data-auth class="primary">登入／註冊</button>`;return}
 const tab=route().q.get('tab')||'requests';app.innerHTML=heading('我的隊伍','遊戲中的同伴，也在這本手札裡相互支援。')+`<div class="filters"><select id="team-select" aria-label="選擇隊伍">${teams.length?teams.map(t=>`<option value="${t.id}" ${t.id===teamId?'selected':''}>${h(t.name)}</option>`).join(''):'<option value="">尚未加入隊伍</option>'}</select><button data-team-create>建立隊伍</button><button data-team-join>輸入邀請碼</button></div>${teamId?`<div class="chips"><a class="btn ${tab==='requests'?'active':''}" href="#team?tab=requests">需求與邀約</a><a class="btn ${tab==='compare'?'active':''}" href="#team?tab=compare">隊員收藏比較</a><a class="btn ${tab==='records'?'active':''}" href="#team?tab=records">據點與里程碑</a><a class="btn ${tab==='members'?'active':''}" href="#team?tab=members">隊伍成員</a></div><div id="team-content" class="loading">正在讀取隊伍…</div>`:empty('先建立一個隊伍，或向隊長取得邀請碼。')}`;
 if(!teamId)return;
 const members=check(await db.from('team_members').select('user_id').eq('team_id',teamId));const ids=members.map(m=>m.user_id);const profiles=check(await db.from('profiles').select('*').in('id',ids));players=new Map(profiles.map(p=>[p.id,p]));
 if(tab==='compare')await compareTeam();else if(tab==='records')await recordsTeam();else if(tab==='members')membersTeam(profiles);else await requestsTeam();
}
async function requestsTeam(){requests=check(await db.from('requests').select('*').eq('team_id',teamId).order('created_at',{ascending:false}).limit(200));$('#team-content').className='';$('#team-content').innerHTML=`<div class="actions"><button class="primary" data-request-new>＋ 發布需求／邀約</button><button data-team-refresh>重新整理</button></div><p class="muted">開著網站時接收站內即時通知。只對同隊可見；發布者確認完成。</p><div class="grid">${requests.map(r=>requestCard(r)).join('')}</div>${requests.length?'':empty('隊伍目前沒有申請。可以先發布一張材料需求或遠征邀約。')}`}
const statusNames={open:'等待接單',claimed:'進行中',submitted:'待發布者確認',completed:'已完成',cancelled:'已取消'};
function playerName(id){return players.get(id)?.game_id||'隊員'}
function requestCard(r){let actions='';if(r.status==='open'&&r.author_id!==user.id)actions+=`<button data-request-action="claim" data-rid="${r.id}">接單</button>`;if(r.status==='claimed'&&r.assignee_id===user.id)actions+=`<button data-request-action="submit" data-rid="${r.id}">提交完成</button><button data-request-action="release" data-rid="${r.id}">釋出接單</button>`;if(r.status==='submitted'&&r.author_id===user.id)actions+=`<button class="primary" data-request-action="complete" data-rid="${r.id}">確認完成</button><button data-request-action="reopen" data-rid="${r.id}">退回</button>`;if(['open','claimed','submitted'].includes(r.status)&&r.author_id===user.id)actions+=`<button data-request-action="cancel" data-rid="${r.id}">取消</button>`;
 return `<section class="card request-card"><span class="status">${r.kind==='item'?'⚒ 物品申請':'⚑ 任務邀約'} · ${statusNames[r.status]}</span><h3>${h(r.title)}</h3><p class="detail-body">${h(r.body)}</p><p>${r.quantity?'數量：'+r.quantity+'　':''}${h(r.location)}</p>${r.scheduled_at?`<p>時間：${h(new Date(r.scheduled_at).toLocaleString('zh-TW',{timeZone:'Asia/Singapore'}))}（UTC+8）</p>`:''}<small>${h(playerName(r.author_id))} 發布${r.assignee_id?' · '+h(playerName(r.assignee_id))+' 接單':''}</small><div class="actions">${actions}<button data-comments="${r.id}">留言／詳情</button></div></section>`;
}
function newRequest(){modal('發布隊伍需求',`<form id="request-form" class="form-grid"><label>類型<select name="kind"><option value="item">物品申請</option><option value="mission">任務邀約</option></select></label><label>標題<input name="title" maxlength="160" required placeholder="例如：建築工小屋缺橡木原木"></label><label>數量<input name="quantity" type="number" min="1" max="1000000" placeholder="任務邀約可留空"></label><label>用途／準備／分工<textarea name="body" maxlength="4000"></textarea></label><label>交付／集合地點<input name="location" maxlength="200" placeholder="維度、XYZ、入口或據點名稱"></label><label>預定時間（UTC+8）<input name="scheduled_at" type="datetime-local"></label><button class="primary">發布</button></form>`);$('#request-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const d=Object.fromEntries(new FormData(e.target));check(await db.from('requests').insert({team_id:teamId,author_id:user.id,...d,quantity:d.quantity?Number(d.quantity):null,scheduled_at:d.scheduled_at?new Date(d.scheduled_at+':00+08:00').toISOString():null}));closeModal();toast('已發布給隊伍');await render()}catch(e){showError(e)}finally{b.disabled=false}}}
async function comments(id){const r=requests.find(x=>x.id===id);if(!r)return;const rows=check(await db.from('request_comments').select('*').eq('request_id',id).order('created_at'));modal(r.title,`<p>${h(r.body)}</p><div class="mini-list">${rows.map(c=>`<section class="panel"><small>${h(playerName(c.author_id))} · ${h(new Date(c.created_at).toLocaleString('zh-TW'))}</small><p class="detail-body">${h(c.body)}</p></section>`).join('')||'<p class="muted">還沒有留言。</p>'}</div><form id="comment-form" class="form-grid"><label>回覆<textarea name="body" required maxlength="2000"></textarea></label><button class="primary">送出留言</button></form>`);$('#comment-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{check(await db.from('request_comments').insert({request_id:id,author_id:user.id,body:new FormData(e.target).get('body')}));await comments(id)}catch(e){showError(e)}finally{b.disabled=false}}}
async function compareTeam(){teamRows=[];for(let i=0;;i+=1000){const rows=check(await db.rpc('team_progress',{t:teamId}).order('user_id').order('record_key').range(i,i+999));teamRows.push(...rows);if(rows.length<1000)break}const shared=new Map();teamRows.forEach(r=>{if(!shared.has(r.user_id))shared.set(r.user_id,{name:r.game_id,done:new Set()});if(r.completed)shared.get(r.user_id).done.add(r.record_key)});const all=[...collections.filter(x=>x.collectible),...advancements.map(x=>({key:'advancement:'+x.id,title:x.title,category:'advancements'}))];const cats=Object.entries(CATEGORIES).filter(([k])=>k!=='strategy');$('#team-content').className='';$('#team-content').innerHTML=`<h2>隊員收藏進度</h2><p class="muted">只顯示開啟分享的隊員。各人的筆記與條件細節都保持私人。</p><div class="grid">${[...shared.values()].map(p=>`<div class="card"><h3>${h(p.name)}</h3>${cats.map(([k,v])=>{const rows=all.filter(x=>x.category===k);return `<small>${v}</small>${bar(rows.filter(x=>p.done.has(x.key)).length,rows.length)}`}).join('')}</div>`).join('')}</div><section class="panel"><h3>逐項比較</h3><form id="compare-filter" class="form-grid"><select name="category" aria-label="比較收藏類型">${cats.map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><input name="q" aria-label="搜尋比較項目" placeholder="搜尋收藏名稱…"><button>套用</button></form><div id="compare-table"></div></section>`;
 let comparePage=1;function draw(cat,needle=''){const rows=all.filter(x=>x.category===cat&&x.title.toLowerCase().includes(needle.toLowerCase()));$('#compare-table').innerHTML=`<p class="muted">${rows.length} 筆 · 第 ${comparePage} / ${Math.max(1,Math.ceil(rows.length/60))} 頁</p><div class="table-scroll"><table><thead><tr><th>收藏項目</th>${[...shared.values()].map(p=>`<th>${h(p.name)}</th>`).join('')}</tr></thead><tbody>${rows.slice((comparePage-1)*60,comparePage*60).map(x=>`<tr><td><a href="#${x.category==='advancements'?'advance/'+enc(x.key.slice(12)):'record/'+enc(x.key)}">${h(x.title)}</a></td>${[...shared.values()].map(p=>`<td class="${p.done.has(x.key)?'checkmark':''}">${p.done.has(x.key)?'✓ 已完成':'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="pager"><button id="compare-prev" ${comparePage===1?'disabled':''}>← 上頁</button><button id="compare-next" ${comparePage*60>=rows.length?'disabled':''}>下頁 →</button></div>`;$('#compare-prev').onclick=()=>{comparePage--;draw(cat,needle)};$('#compare-next').onclick=()=>{comparePage++;draw(cat,needle)}}draw('equipment');$('#compare-filter').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);comparePage=1;draw(d.get('category'),d.get('q'))};}
async function recordsTeam(){teamRecords=check(await db.from('team_records').select('*').eq('team_id',teamId).order('updated_at',{ascending:false}).limit(200));$('#team-content').className='';$('#team-content').innerHTML=`<button class="primary" data-record-new>＋ 新增據點／計畫／里程碑</button><div class="grid" style="margin-top:18px">${teamRecords.map(r=>`<section class="card"><span class="tag">${{base:'共享據點',plan:'建設計畫',milestone:'世界里程碑'}[r.kind]}</span><h3>${h(r.title)}</h3><p class="detail-body">${h(r.body)}</p><small>${h(playerName(r.author_id))}</small>${r.author_id===user.id||teams.find(t=>t.id===teamId)?.owner_id===user.id?`<button data-record-edit="${r.id}">編輯</button>`:''}</section>`).join('')}</div>`}
function newTeamRecord(id){const old=teamRecords.find(x=>x.id===id);modal(old?'編輯共享紀錄':'新增共享紀錄',`<form id="team-record-form" class="form-grid"><label>類型<select name="kind" ${old?'disabled':''}>${[['base','共享據點'],['plan','建設計畫'],['milestone','世界里程碑']].map(([k,v])=>`<option value="${k}" ${old?.kind===k?'selected':''}>${v}</option>`).join('')}</select></label><label>標題<input name="title" required maxlength="160" value="${h(old?.title||'')}"></label><label>內容<textarea name="body" maxlength="8000" placeholder="維度、XYZ、建設分工、注意事項…">${h(old?.body||'')}</textarea></label><button class="primary">保存</button></form>`);$('#team-record-form').onsubmit=async e=>{e.preventDefault();try{const d=Object.fromEntries(new FormData(e.target));if(old)check(await db.from('team_records').update({title:d.title,body:d.body,updated_at:new Date().toISOString()}).eq('id',id));else check(await db.from('team_records').insert({...d,team_id:teamId,author_id:user.id}));closeModal();await render()}catch(e){showError(e)}}}
function membersTeam(rows){const owner=teams.find(t=>t.id===teamId)?.owner_id===user.id;$('#team-content').className='';$('#team-content').innerHTML=`<h2>隊伍成員</h2><div class="grid">${rows.map(p=>`<div class="card"><h3>${h(p.game_id)}</h3><small>${p.id===teams.find(t=>t.id===teamId)?.owner_id?'隊長':'隊員'} · ${p.share_progress?'分享收藏完成進度':'已關閉進度分享'}</small></div>`).join('')}</div>${owner?'<button data-invite style="margin-top:18px">產生邀請碼</button>':''}<p class="muted">邀請碼有效七天，可供 20 次加入。遊戲內領地權限需另行設定。</p>`}
async function adminPage(){if(!isAdmin){app.innerHTML=empty('需要管理員權限');return}const rows=check(await db.rpc('admin_players'));app.innerHTML=heading('管理員控制台','審批新玩家，或協助重設網站帳號。')+`<div class="grid">${rows.map(p=>`<section class="card"><span class="tag">${p.is_admin?'管理員':p.approved?'已核准':'待審批'}</span><h3>${h(p.game_id)}</h3><div class="actions">${!p.is_admin?`<button data-approve="${p.user_id}" data-allow="${!p.approved}">${p.approved?'停用帳號':'核准加入'}</button><button data-promote="${p.user_id}">設為管理員</button>`:''}<button data-admin-reset="${h(p.game_id)}">重設帳號密碼</button></div></section>`).join('')}</div>${notice('管理員重設會讓既有登入失效，產生一次性的復原碼。請自行確認玩家身分，再將復原碼私下交給本人。')}`}
function guide(slug){const atlas=ATLASES.find(a=>a[4]===slug);if(!atlas){app.innerHTML=empty('找不到攻略');return}const q=route().q;mountAtlas(atlas,{item:q.get('item'),query:q.get('q')||''})}
async function render(){const sequence=++routeSequence,{path,q}=route();NAV.forEach(([id])=>{document.querySelectorAll(`[data-nav="${id}"]`).forEach(e=>e.classList.toggle('active',(path[0]===id||(id==='collections'&&['record','guide'].includes(path[0])))))});app.classList.remove('route-enter');document.body.classList.remove('atlas-open');document.body.classList.toggle('full-guide',path[0]==='guide'&&q.get('full')==='1');currentGuide=null;
 try{switch(path[0]){case'home':home();break;case'journey':journey(path[1]);break;case'article':article(path[1]);break;case'collections':catalog();break;case'record':record(path.slice(1).join('/'));break;case'advancements':advanceList();break;case'advance':advance(path.slice(1).join('/'));break;case'search':globalSearch(q.get('q')||'');break;case'me':me();break;case'team':await team();break;case'admin':await adminPage();break;case'guide':guide(path[1]);break;default:home()}if(sequence!==routeSequence)return;app.classList.add('route-enter');}catch(e){app.innerHTML=notice('無法讀取資料：'+e.message,true)+`<button data-refresh-page>再試一次</button>`;showError(e)}
}
document.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;try{
 if(b.id==='modal-close')closeModal();else if(b.id==='theme-toggle'){document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('iaa-theme',document.documentElement.dataset.theme);$('#guide-frame')?.contentWindow.postMessage({type:'guide-theme',theme:document.documentElement.dataset.theme,motion:document.documentElement.dataset.motion},location.origin)}else if(b.id==='account-open'){if(user)go('me');else openAuth()}else if(b.id==='search-open'){modal('搜尋世界手札',`<form id="quick-search" class="form-grid"><input name="q" aria-label="搜尋關鍵字" placeholder="名稱、配方、技能、首領…" autofocus required><button class="primary">搜尋</button></form>`);$('#quick-search').onsubmit=e=>{e.preventDefault();const q=new FormData(e.target).get('q');closeModal();pageNumber=1;go('search?q='+enc(q))}}
 else if(b.hasAttribute('data-auth'))openAuth();else if(b.dataset.authMode)openAuth(b.dataset.authMode);else if(b.dataset.recipe)itemRecipe(b.dataset.recipe);else if(b.dataset.page){pageNumber=Number(b.dataset.page);await render();window.scrollTo(0,80)}
 else if(b.dataset.atlasNote){if(needAccount())modal('我的私人筆記',notesPanel(b.dataset.atlasNote))}
 else if(b.hasAttribute('data-refresh-account')){await loadAccount();await render()}
 else if(b.hasAttribute('data-logout')){check(await db.auth.signOut());await loadAccount();await render()}
 else if(b.hasAttribute('data-export')){const blob=new Blob([JSON.stringify({gameId:profile.game_id,exportedAt:new Date().toISOString(),progress:[...progress.values()]},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='帝國紀元-我的紀錄.json';a.click();URL.revokeObjectURL(url)}
 else if(b.hasAttribute('data-copy-secret')){await navigator.clipboard.writeText($('#recovery-secret').textContent);toast('已複製，請保存到私人位置')}
 else if(b.hasAttribute('data-close-secret'))closeModal();
 else if(b.hasAttribute('data-team-create')||b.hasAttribute('data-team-join')){const join=b.hasAttribute('data-team-join');modal(join?'加入隊伍':'建立隊伍',`<form id="team-action-form" class="form-grid"><label>${join?'邀請碼':'隊伍名稱'}<input name="value" required maxlength="${join?32:80}"></label><button class="primary">${join?'加入':'建立'}</button></form>`);$('#team-action-form').onsubmit=async e=>{e.preventDefault();try{const value=new FormData(e.target).get('value');const t=check(await db.rpc(join?'join_team':'create_team',join?{c:value}:{n:value}));localStorage.setItem('iaa-team-'+user.id,t);await loadTeams();closeModal();await render()}catch(e){showError(e)}}}
 else if(b.hasAttribute('data-invite')){const code=check(await db.rpc('create_invite',{t:teamId}));modal('隊伍邀請碼',`<p>有效七天，最多 20 次加入。請只分享給隊友。</p><p class="secret" id="recovery-secret">${h(code)}</p><button data-copy-secret>複製邀請碼</button>`)}
 else if(b.hasAttribute('data-request-new'))newRequest();else if(b.dataset.requestAction){b.disabled=true;check(await db.rpc('request_action',{rid:b.dataset.rid,action:b.dataset.requestAction}));toast('申請狀態已更新');await render()}
 else if(b.dataset.comments)await comments(b.dataset.comments);else if(b.hasAttribute('data-record-new'))newTeamRecord();else if(b.dataset.recordEdit)newTeamRecord(b.dataset.recordEdit);else if(b.hasAttribute('data-team-refresh')||b.hasAttribute('data-refresh-page'))await render();
 else if(b.dataset.approve){check(await db.rpc('admin_approve',{uid:b.dataset.approve,allow:b.dataset.allow==='true'}));await render()}
 else if(b.dataset.promote){const uid=b.dataset.promote;modal('授予網站管理權限','<p>此玩家將能核准其他帳號與協助重設密碼。</p><button class="primary" id="promote-confirm">確認授予</button>');$('#promote-confirm').onclick=async()=>{try{check(await db.rpc('admin_make',{uid}));closeModal();await render()}catch(e){showError(e)}}}
 else if(b.dataset.adminReset){const gameId=b.dataset.adminReset;modal('協助重設帳號',`<p>將使 ${h(gameId)} 的既有登入失效並產生新的復原碼。請先確認玩家身分。</p><button id="admin-reset-confirm" class="primary">產生一次性復原碼</button>`);$('#admin-reset-confirm').onclick=async()=>{try{const session=check(await db.auth.getSession()).session;const r=await fetch(cfg.supabaseUrl+'/functions/v1/player-auth',{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg.supabaseKey,'x-public-key':cfg.supabaseKey,Authorization:'Bearer '+session.access_token},body:JSON.stringify({action:'admin-reset',gameId,password:'admin-operation-placeholder'})});const data=await r.json();if(!r.ok)throw Error(data.error);modal('新的復原碼',`<p>請私下交給 ${h(gameId)}。對方在「復原帳號」設定自己的新密碼。</p><p class="secret" id="recovery-secret">${h(data.recoveryCode)}</p><button data-copy-secret>複製</button>`)}catch(e){showError(e)}}}
 }catch(e){showError(e);if(b.tagName==='BUTTON')b.disabled=false}});
document.addEventListener('change',async e=>{const x=e.target;try{if(x.dataset.complete){const checked=x.checked;if(!needAccount()){x.checked=!checked;return}x.disabled=true;try{await saveRecord(x.dataset.complete,{completed:checked});toast('收藏進度已保存')}catch(e){x.checked=!checked;throw e}finally{x.disabled=false}}
 else if(x.dataset.criterion){if(!needAccount()){x.checked=!x.checked;return}const key=x.dataset.record,checklist={...(progress.get(key)?.checklist||{}),[x.dataset.criterion]:x.checked};await saveRecord(key,{checklist})}
 else if(x.id==='share-progress'){if(!needAccount())return;check(await db.from('profiles').update({share_progress:x.checked}).eq('id',user.id));profile.share_progress=x.checked;toast(x.checked?'已開啟同隊進度分享':'已關閉同隊進度分享')}
 else if(x.id==='reduce-motion'){document.documentElement.dataset.motion=x.checked?'off':'on';localStorage.setItem('iaa-motion',x.checked?'off':'on')}
 else if(x.id==='team-select'){teamId=x.value;await subscribeTeam();await render()}}catch(e){showError(e)}});
document.addEventListener('submit',async e=>{if(!e.target.dataset.note)return;e.preventDefault();if(!needAccount())return;const b=e.target.querySelector('button');b.disabled=true;try{await saveRecord(e.target.dataset.note,{notes:new FormData(e.target).get('notes')});toast('私人筆記已保存')}catch(e){showError(e)}finally{b.disabled=false}});
window.addEventListener('message',e=>{const iframe=$('#guide-frame');if(e.origin!==location.origin||e.source!==iframe?.contentWindow||!currentGuide)return;const d=e.data;if(d?.slug!==currentGuide.slug)return;if(d.type==='guide-ready')iframe.contentWindow.postMessage({type:'atlas-open',id:currentGuide.item,query:currentGuide.query,reference:currentGuide.reference,done:currentGuide.done,view:currentGuide.category==='companions'?'pets':currentGuide.category==='mounts'?'mounts':'boss'},location.origin);if(d.type==='guide-progress'&&active&&d.data&&typeof d.data==='object'){clearTimeout(guideTimer);const slug=d.slug,data=d.data,uid=user.id;guideTimer=setTimeout(async()=>{if(!active||user?.id!==uid)return;try{const before=writeGuide(slug,progress.get('guide:'+slug)?.checklist||{},progress,collections),old=readGuide(slug,before),next=readGuide(slug,data),keys=new Set([...old.keys(),...next.keys()]);for(const key of keys){if(!collections.some(c=>c.key===key&&c.collectible))continue;const a=old.get(key)||{completed:false},b=next.get(key)||{completed:false},patch={};if(a.completed!==b.completed)patch.completed=b.completed;if('notes'in b&&a.notes!==b.notes)patch.notes=b.notes;if(Object.keys(patch).length)await saveRecord(key,patch)}await saveRecord('guide:'+slug,{checklist:data});}catch(e){showError(e)}},500)}});
window.addEventListener('hashchange',()=>{pageNumber=1;window.scrollTo(0,0);render().catch(showError)});
window.addEventListener('online',()=>{toast('已恢復網路連線');if(teamId)subscribeTeam().catch(showError)});
async function init(){try{cfg=await fetch('site-config.json').then(r=>r.json());document.title=cfg.siteTitle;$('.side-note p').textContent=cfg.taglineZh;[articles,collections,advancements,icons,summary,recipes,originals,names]=await Promise.all(['articles','collections','advancements','icons','summary','tutorial-recipes','originals','names'].map(name=>fetch('data/'+name+'.json').then(r=>{if(!r.ok)throw Error('攻略資料載入失敗');return r.json()})));db=createClient(cfg.supabaseUrl,cfg.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true}});$('#desktop-nav').innerHTML=NAV.map(([id,icon,name])=>`<a data-nav="${id}" href="#${id}"><span class="nav-icon">${icon}</span>${name}</a>`).join('');$('#mobile-nav').innerHTML=NAV.map(([id,icon,name])=>`<a data-nav="${id}" href="#${id}"><span class="nav-icon">${icon}</span>${name}</a>`).join('');await render();try{await loadAccount()}catch(e){cloudUnavailable=true;active=false;toast('雲端紀錄暫時無法連線，攻略仍可閱讀。請稍後重試。',true)}await render();db.auth.onAuthStateChange((event,session)=>{if(event==='TOKEN_REFRESHED')user=session?.user||null;if(event==='SIGNED_OUT'&&user){user=null;active=false;progress.clear();if(channel){db.removeChannel(channel);channel=null}updateAccountLabel();render().catch(showError)}})}catch(e){app.innerHTML=notice('載入失敗，請確認網路後重新整理。'+e.message,true)}}
init();
