let dispose=()=>{};
export function stopAssistantAdmin(){dispose();dispose=()=>{}}
export function mountAssistantAdmin(root,{db,cfg,h}){
 stopAssistantAdmin();let alive=true,busy=false,sequence=0,pending=[];const controller=new AbortController();
 root.innerHTML='<h2>小助手問答管理</h2><p role="status" data-quota-status>正在讀取…</p><div data-quota-summary></div><div data-quota-providers class="grid"></div><details><summary>玩家每日問答上限</summary><p>每天臺灣時間 00:00 重置；0 表示暫停該玩家的 AI 問答。調整立即生效，已使用次數會保留。全站仍有每日 400 問的免費保護上限。</p><div data-quota-players class="grid"></div></details><details><summary>Gemini 每日請求保護</summary><p>請先在 Google AI Studio 確認目前模型的每日請求上限，再填入這裡。一次聊天可能包含規劃與回答等多次 API 呼叫；此設定只保護本網站，不代表供應商已確認的即時餘額。</p><form data-gemini-budget class="actions"><label>已確認的每日請求上限<input name="limit" type="number" min="1" max="100000" step="1" placeholder="尚未設定" aria-label="Gemini 每日請求上限"></label><button type="submit">保存保護上限</button><button type="button" data-budget-clear>清除設定</button></form><a href="https://aistudio.google.com/rate-limit?project=gen-lang-client-0388317824" target="_blank" rel="noopener">Google AI Studio 用量與上限 ↗</a></details><div class="actions"><button type="button" data-quota-refresh>更新用量</button></div>';
 const status=root.querySelector('[data-quota-status]'),date=x=>new Date(x).toLocaleString('zh-TW',{hour12:false}),num=x=>Number(x).toLocaleString('zh-TW');
 async function api(change){const {data,error}=await db.auth.getSession();if(error||!data.session)throw Error('請重新登入管理員帳號。');const r=await fetch(cfg.aiEndpoint+'/admin/quotas',{method:change?'POST':'GET',headers:{Authorization:'Bearer '+data.session.access_token,...(change?{'Content-Type':'application/json'}:{})},...(change?{body:JSON.stringify(change)}:{}),cache:'no-store',signal:controller.signal});const body=await r.json();if(!r.ok)throw Error(body.error||'讀取失敗。');return body}
 function paint(data){
  root.querySelector('[data-quota-summary]').textContent=`全站每日上限 ${data.global.limit} 問，今天已使用 ${data.global.used} 問，網站上限還剩 ${data.global.remaining} 問；仍以免費 API 可用額度為準。`;
  root.querySelector('[data-quota-providers]').innerHTML=data.providers.map(p=>`<article class="card"><h3>${p.provider==='gemini'?'Gemini':'Workers AI'}</h3><p>${p.available?'目前可使用':'目前暫停'}${p.retryAt?' · 可重試時間 '+h(date(p.retryAt)):''}</p><p><strong>供應商當日實際餘額：${p.providerRemaining===null?'尚未取得':num(p.providerRemaining)}</strong></p><p>網站${p.provider==='gemini'?'請求':'Neurons'}保護餘額：${p.siteRemaining===null?'尚未設定上限':num(p.siteRemaining)+'／'+num(p.siteBudget)}</p><p>${h(p.measurement)}：${num(p.siteConsumed)}</p><p>今日成功回應 ${p.usage?.successes||0} 次，失敗請求 ${p.usage?.errors||0} 次。</p><p class="muted">${h(p.providerRemainingReason)}<br>本日 ${h(p.date)}，依 ${p.provider==='gemini'?'美國太平洋時間':'UTC'} 00:00 重置。${p.trackingSince?'用量記錄自 '+h(date(p.trackingSince))+' 開始。':'更新上線前的請求未計入新記錄。'}</p>${p.provider==='cloudflare'?'<a href="https://dash.cloudflare.com/?to=/:account/ai/workers-ai" target="_blank" rel="noopener">Cloudflare 官方用量 ↗</a>':''}</article>`).join('');
  const list=root.querySelector('[data-quota-players]');
  if(!list.children.length)list.innerHTML=data.players.map(p=>`<form class="card form-grid" data-player-quota="${h(p.userId)}"><h3>${h(p.name)}</h3><p data-player-usage></p><label>每日 AI 問答上限<input name="limit" aria-label="${h(p.name)} 每日 AI 問答上限" type="number" min="0" max="400" step="1" required value="${p.limit}"></label><div class="actions"><button type="submit">保存上限</button><button type="button" data-limit-default>恢復預設 50 問</button></div></form>`).join('');
  for(const p of data.players){const form=[...list.children].find(x=>x.dataset.playerQuota===p.userId);if(form)form.querySelector('[data-player-usage]').textContent=`今天已用 ${p.used} 問，還可問 ${p.remaining} 問；目前上限 ${p.limit}${p.custom?'（個別設定）':'（預設）'}。`}
  const budget=root.querySelector('[data-gemini-budget] input');if(document.activeElement!==budget&&!budget.dataset.edited)budget.value=data.providers.find(p=>p.provider==='gemini').siteBudget??'';
  status.textContent=`最後更新 ${date(data.updatedAt)} · 開啟此頁時每 15 秒更新。`;
 }
 async function refresh(change){if(!alive)return;if(busy){if(change)pending.push(change);return}busy=true;const current=++sequence;try{const data=await api(change);if(alive&&current===sequence){paint(data);if(change){status.textContent='設定已保存並立即生效。 '+status.textContent;const form=change.userId?[...root.querySelectorAll('[data-player-quota]')].find(x=>x.dataset.playerQuota===change.userId):root.querySelector('[data-gemini-budget]');if(form)form.querySelector('input').value=change.userId?change.limit??50:change.geminiDailyLimit??''}}}catch(e){if(alive&&e.name!=='AbortError')status.textContent='問答管理更新失敗：'+e.message}finally{busy=false;if(pending.length&&alive)void refresh(pending.shift())}}
 root.addEventListener('input',e=>{if(e.target.closest('[data-gemini-budget]'))e.target.dataset.edited='true'});
 root.addEventListener('submit',e=>{e.preventDefault();const form=e.target,limit=Number(form.elements.limit.value);if(!form.reportValidity())return;void refresh(form.dataset.playerQuota?{userId:form.dataset.playerQuota,limit}:{geminiDailyLimit:limit})});
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-quota-refresh'))void refresh();else if(b.hasAttribute('data-limit-default'))void refresh({userId:b.closest('form').dataset.playerQuota,limit:null});else if(b.hasAttribute('data-budget-clear'))void refresh({geminiDailyLimit:null})});
 const timer=setInterval(()=>{if(!document.hidden)void refresh()},15000);dispose=()=>{alive=false;controller.abort();clearInterval(timer)};void refresh();
}
