export const PRESETS=[['steve','史蒂夫'],['alex','艾莉克絲'],['creeper','苦力帕'],['zombie','殭屍'],['skeleton','骷髏'],['enderman','終界使者'],['villager','村民'],['piglin','豬布林'],['wither_skeleton','凋零骷髏'],['husk','屍殼'],['drowned','沉屍'],['stray','流髑']];
export function avatarSource(p,cfg){if(p?.avatar_path&&p.id&&p.avatar_path===p.id+'/avatar.png'&&p.avatar_url)return p.avatar_url;const id=PRESETS.some(([id])=>id===p?.avatar_preset)?p.avatar_preset:'steve';return 'assets/avatars/'+id+'.svg'}
export function avatarImage(p,cfg,h,cls=''){return `<img class="player-avatar ${h(cls)}" data-avatar-user="${h(p?.id||'')}" src="${h(avatarSource(p,cfg))}" alt="" width="32" height="32">`}
export async function resolveAvatars(rows,db){const valid=rows.filter(p=>p?.avatar_path&&p.id&&p.avatar_path===p.id+'/avatar.png');if(!valid.length)return;try{const {data,error}=await db.storage.from('player-avatars').createSignedUrls([...new Set(valid.map(p=>p.avatar_path))],300);if(error)return;for(const p of valid){const signed=data.find(x=>x.path===p.avatar_path&&!x.error)?.signedUrl;p.avatar_url=signed? signed+(signed.includes('?')?'&':'?')+'v='+encodeURIComponent(p.avatar_updated_at):null}}catch{}}
export function openAvatarEditor({profile,user,db,cfg,h,modal,check,onSaved,onError}){
 modal('編輯頭像',`<div class="avatar-presets">${PRESETS.map(([id,label])=>`<button data-avatar-preset="${id}" aria-label="${h(label)}" aria-pressed="${!profile.avatar_path&&profile.avatar_preset===id}" data-item-hint="${h(label)}"><img class="player-avatar" src="assets/avatars/${id}.svg" alt="" width="48" height="48"></button>`).join('')}</div><form id="avatar-upload" class="form-grid"><label>上傳自己的頭像<input id="avatar-file" type="file" accept="image/png,image/jpeg,image/webp"></label><div id="avatar-upload-preview"></div><p id="avatar-error" role="status"></p><button class="primary" disabled>儲存上傳頭像</button></form>`);
 const body=document.getElementById('modal-body'),form=document.getElementById('avatar-upload');let blob=null,busy=false;
 async function save(patch){const updated={...patch,avatar_updated_at:new Date().toISOString()};check(await db.from('profiles').update(updated).eq('id',user.id));Object.assign(profile,updated);profile.avatar_url=null;if(updated.avatar_path)await resolveAvatars([profile],db);onSaved(profile)}
 body.querySelectorAll('[data-avatar-preset]').forEach(button=>button.onclick=async()=>{if(busy)return;busy=true;try{await save({avatar_preset:button.dataset.avatarPreset,avatar_path:null});}catch(e){onError(e)}finally{busy=false}});
 document.getElementById('avatar-file').onchange=async e=>{blob=null;form.querySelector('button').disabled=true;document.getElementById('avatar-error').textContent='';const f=e.target.files[0];if(!f)return;try{if(!['image/png','image/jpeg','image/webp'].includes(f.type))throw Error('請選擇 PNG、JPG 或 WebP 圖片');if(f.size>10*1024*1024)throw Error('圖片請小於 10 MB');const bitmap=await createImageBitmap(f);if(!bitmap.width||!bitmap.height)throw Error('無法讀取圖片');const canvas=document.createElement('canvas');canvas.width=256;canvas.height=256;const context=canvas.getContext('2d'),side=Math.min(bitmap.width,bitmap.height);context.drawImage(bitmap,(bitmap.width-side)/2,(bitmap.height-side)/2,side,side,0,0,256,256);bitmap.close();blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('圖片轉換失敗');const preview=document.getElementById('avatar-upload-preview');preview.replaceChildren(canvas);canvas.className='avatar-preview';form.querySelector('button').disabled=false}catch(err){document.getElementById('avatar-error').textContent=err.message}};
 form.onsubmit=async e=>{e.preventDefault();if(!blob||busy)return;busy=true;const button=form.querySelector('button');button.disabled=true;try{const path=user.id+'/avatar.png';check(await db.storage.from('player-avatars').upload(path,blob,{contentType:'image/png',cacheControl:'3600',upsert:true}));await save({avatar_path:path});}catch(err){onError(err);button.disabled=false}finally{busy=false}};
}
