export async function mountColonyGuide(root,{h,image,names}){
 const data=await fetch('data/colony-guide.json').then(r=>r.json()),research=new Map(data.research.map(r=>[r.id,r])),buildings=new Map(data.buildings.map(b=>['minecolonies:'+b.id,b]));
 const label=id=>buildings.get(id)?.title||names[id]||id.replace('minecraft:','').replace('minecolonies:','');
 const title=id=>research.get(id)?.title||id;
 function chain(r,seen=new Set()){if(!r||seen.has(r.id))return [];seen.add(r.id);return [...chain(research.get(r.parentResearch),seen),r]}
 const prerequisites=r=>(r.requirements||[]).map(x=>x.type==='minecolonies:alternate-building'?(x['alternate-buildings']||[]).map(label).join(' 或 ')+'，其中一種類型總等級至少 '+x.level:x.building?label(x.building)+(x.type==='minecolonies:single-building'?'任一棟至少':'總等級至少')+' '+x.level+' 級':x.research?title(x.research):'需完成節點列出的前置條件').join('；');
 const costs=r=>(r.costs||[]).map(c=>`${c.item?image(c.item):''}${h(c.item?label(c.item):c.tag==='minecraft:planks'?'任意木板':c.tag?label(c.tag):'指定材料')} × ${c.quantity||1}`).join('、');
 root.innerHTML=`<article class="article colony-guide"><h1>殖民地建築與職業</h1><p>MineColonies ${h(data.version)}</p><section class="panel"><h2>放置、建造與擴張</h2><ol><li>使用建築工具選擇風格與建築藍圖，移動、旋轉預覽後確認小屋方塊位置。先檢查藍圖最高等級的佔地，避免升級時穿入鄰屋。</li><li>右鍵小屋方塊，在建築選項提出建造或升級工作單。建築工需要等級足以接單的小屋、工具與需求材料；一般建築由 0 級建至 1 級，之後逐級升級。</li><li>領地以區塊計算，1 區塊＝16×16 格。初始半徑的程式預設為 4 區塊，擴張最遠半徑預設 20 區塊；建築周圍的佔領半徑如下表。領地會合併，與建築實際佔地大小不同。</li><li>小屋方塊必須在你的殖民地領地內；建築工擴張受市政廳中心最大距離限制，不能一路延伸到無限遠。藍圖角落也參與建築領地登記。</li></ol><p>人口上限的程式預設為 250；實際還需要住房與相關研究。上列是此版本預設值，伺服器的 minecolonies-server.toml 可改寫，網站不把它當作已確認的伺服器值。</p></section><form class="filters" id="colony-search"><input name="q" aria-label="搜尋建築、職業或研究" placeholder="搜尋建築、職業或研究"><select name="view"><option value="buildings">54 種建築</option><option value="research">208 個研究節點</option></select><button>查詢</button></form><div id="colony-results"></div></article>`;
 function draw(q='',view='buildings'){
  const target=root.querySelector('#colony-results'),needle=q.trim().toLowerCase();
  if(view==='research'){target.innerHTML=data.research.filter(r=>(r.title+' '+r.subtitle+' '+r.id).toLowerCase().includes(needle)).map(r=>`<details class="colony-building"><summary>${h(r.title)} · ${r.researchLevel} 級研究</summary><p>${r.effectsText.map(h).join('；')}</p>${r.researchLevel>=6?'<p>本分支的最高層研究只能完成一個；先比較其他第六層節點再選擇。</p>':''}<p>分支：${h({'minecolonies:civilian':'民生','minecolonies:combat':'戰鬥','minecolonies:technology':'科技'}[r.branch]||r.branch)}；大學至少 ${Math.min(5,r.researchLevel)} 級。</p>${r.parentResearch?`<p>前置：${chain(r).slice(0,-1).map(x=>h(x.title)).join(' → ')}</p>`:''}<p>建築條件：${h(prerequisites(r)||'無額外建築條件')}</p><p>研究材料：${costs(r)}</p></details>`).join('');return}
  target.innerHTML=data.buildings.filter(b=>(b.title+' '+b.operation+' '+b.jobs.map(j=>j.primary+' '+j.secondary+' '+j.job).join(' ')).toLowerCase().includes(needle)).map(b=>`<details class="colony-building"><summary>${image(b.block)} ${h(b.title)} <small>最高 ${b.maxLevel} 級</small></summary><p>${h(b.operation)}</p><h3>建造前提與後續分支</h3>${b.unlocks.length?b.unlocks.map(id=>{const r=research.get(id);return `<p>解鎖研究：${chain(r).map(x=>h(x.title)).join(' → ')}；大學 ${Math.min(5,r.researchLevel)} 級。${h(prerequisites(r))}。</p><p>此節點材料：${costs(r)}</p>`}).join(''):'<p>沒有綁定建築解鎖研究；仍需可用領地、工作單與建築工。</p>'}<p>以本建築作為條件的研究：${data.research.filter(r=>(r.requirements||[]).some(x=>x.building==='minecolonies:'+b.id)).map(r=>`${h(r.title)}（${h(prerequisites(r))}）`).join('；')||'無直接建築條件節點'}</p><h3>佔領範圍</h3><p>${b.radiusNote?h(b.radiusNote):b.radius.map((r,i)=>`${i+1} 級：半徑 ${r} 區塊${r?`（${2*r+1}×${2*r+1} 區塊）`:''}`).join('；')}。</p><h3>職業與能力</h3>${b.jobs.length?b.jobs.map(j=>`<p>${h(j.jobName)}：主要能力 <b>${h(j.primary)}</b>；次要能力：<b>${h(j.secondary)}</b>。${b.id==='builder'?'主要能力影響放置方塊速度，次要能力影響破壞方塊速度。':b.id==='miner'||b.id.includes('quarry')?'這兩項能力分別供採掘與工作速度判定使用。':b.id==='stonesmeltery'||b.id==='glassblower'?'主要能力每滿 10 級，熔煉加速增加 2 刻。':''}${j.craftSpeed?'製作速度使用 '+h(j.craftSpeed)+'，可節省原料的配方改良使用 '+h(j.recipeSkill)+'；不是所有原料都符合可節省標籤。':''}${j.rain?'允許雨天工作。':'未滿級時雨天停工；小屋滿級後可雨天工作。'}</p>`).join(''):'<p>沒有一般工作職業模組；由居民、訪客、配送或附屬建築模組運作。</p>'}${b.settings.length?`<h3>建築內可調整</h3><p>${b.settings.map(h).join('、')}</p>`:''}</details>`).join('');
 }
 draw();root.querySelector('#colony-search').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);draw(f.get('q'),f.get('view'))};
}
