import test from 'node:test';import assert from 'node:assert/strict';
import {GuideService,selectedFacts,approvedUser,providerAnswer,dayKey} from './core.js';
class Store{constructor(){this.values=new Map();this.queue=Promise.resolve()}async get(k){return structuredClone(this.values.get(k))}async put(k,v){this.values.set(k,structuredClone(v))}async delete(keys){for(const key of keys)this.values.delete(key)}async list({prefix,limit,startAfter=''}){return new Map([...this.values].filter(([k])=>k.startsWith(prefix)&&k>startAfter).sort(([a],[b])=>a.localeCompare(b)).slice(0,limit))}transaction(fn){const p=this.queue.then(()=>fn(this));this.queue=p.catch(()=>{});return p}}
const fact={id:'test-id',title:'魔法之眼',search:'魔法之眼',text:'森林豪宅寶箱',labels:[],shard:'one.json'};
function setup(){const storage=new Store(),env={FREE_ONLY_ACK:'true',AI:{run:async()=>({response:{factIds:['test-id']}})},ASSETS:{fetch:async r=>Response.json(r.url.endsWith('manifest.json')?{version:'v1',shards:[{file:'one.json',terms:'魔法之眼'}]}:[fact])}};return {storage,env,service:new GuideService(storage,env)}}
test('only exact supplied facts are returned; fabricated IDs reject the response',()=>{assert.deepEqual(selectedFacts('{"factIds":["unknown"]}',[fact]),[]);assert.deepEqual(selectedFacts({factIds:['test-id','test-id']},[fact]),[fact]);assert.deepEqual(selectedFacts('<script>bad</script>',[fact]),[])});
test('approved account check requires active RPC status',async()=>{const request=new Request('https://test',{headers:{Authorization:'Bearer fake'}}),env={SUPABASE_URL:'https://sb',SUPABASE_KEY:'public'};let calls=0;assert.equal(await approvedUser(request,env,async()=>Response.json(++calls===1?{id:'u'}:{active:false})),null);calls=0;assert.equal(await approvedUser(request,env,async()=>Response.json(++calls===1?{id:'u'}:{active:true})),'u')});
test('Gemini quota failure falls back to Cloudflare',async()=>{let fallback=0;const spent=[];const result=await providerAnswer({GEMINI_API_KEY:'not-real',AI:{run:async()=>{fallback++;return {response:{factIds:['test-id']}}}}},'prompt',async()=>true,async(...args)=>spent.push(args),async()=>new Response('{}',{status:429}));assert.equal(result.provider,'cloudflare');assert.equal(fallback,1);assert(spent.some(x=>x[0]==='gemini'&&x[1]===60000))});
test('no allowed provider returns unavailable without paid route',async()=>{assert.equal(await providerAnswer({AI:{run:()=>assert.fail()}},'prompt',async()=>false,async()=>{}),null)});
test('successful answer, cache, user cap and site cap',async()=>{const {service,storage}=setup();assert.equal((await service.ask('u','魔法之眼')).body.remaining,49);assert.equal((await service.ask('u','魔法之眼')).body.remaining,48);await storage.put('user:'+dayKey()+':u',50);assert.equal((await service.ask('u','魔法之眼')).status,429);await storage.put('global:'+dayKey(),400);assert.equal((await service.ask('other','魔法之眼')).status,429)});
test('failed or ungrounded answers release daily reservation',async()=>{const {service,storage,env}=setup();env.AI.run=async()=>({response:{factIds:['invented']}});assert.equal((await service.ask('u','魔法之眼')).body.facts.length,0);assert.equal(await storage.get('user:'+dayKey()+':u'),0);assert.equal(await storage.get('global:'+dayKey()),0)});
test('Free-only acknowledgement is required before activation',async()=>{const {service,env}=setup();env.FREE_ONLY_ACK='false';assert.equal((await service.ask('u','魔法之眼')).status,503)});
test('app day resets at UTC+8 midnight',()=>{assert.equal(dayKey(Date.parse('2026-10-06T15:59:59Z')),'2026-10-06');assert.equal(dayKey(Date.parse('2026-10-06T16:00:00Z')),'2026-10-07')});
test('concurrent reservations cannot overrun the global daily cap',async()=>{const {service,storage}=setup();await storage.put('global:'+dayKey(),399);const results=await Promise.all([service.ask('a','魔法之眼'),service.ask('b','魔法之眼')]);assert.deepEqual(results.map(r=>r.status).sort(),[200,429]);assert.equal(await storage.get('global:'+dayKey()),400)});
test('expired answer caches and old counters are deleted, current counters remain',async()=>{const {service,storage}=setup();await storage.put('cache:expired',{expires:0});await storage.put('cache:current',{expires:Date.now()+60000});await storage.put('user:2020-01-01:u',1);await storage.put('user:'+dayKey()+':u',1);await service.cleanup();assert.equal(await storage.get('cache:expired'),undefined);assert.equal(await storage.get('user:2020-01-01:u'),undefined);assert(await storage.get('cache:current'));assert.equal(await storage.get('user:'+dayKey()+':u'),1)});
