begin;
create temporary table push_fixture as select gen_random_uuid() owner,gen_random_uuid() member,gen_random_uuid() admin,gen_random_uuid() so,gen_random_uuid() sm,gen_random_uuid() sa,null::uuid team,null::uuid request;
insert into auth.users(id)select owner from push_fixture union all select member from push_fixture union all select admin from push_fixture;
insert into public.profiles(id,game_id)select owner,'PushOwnerTest'from push_fixture union all select member,'PushMemberTest'from push_fixture union all select admin,'PushAdminTest'from push_fixture;
insert into private.accounts(user_id,game_key,recovery_hash,approved)select id,id::text,'test-only',true from public.profiles where id in(select owner from push_fixture union all select member from push_fixture union all select admin from push_fixture);
insert into auth.sessions(id,user_id)select so,owner from push_fixture union all select sm,member from push_fixture union all select sa,admin from push_fixture;
insert into private.admins(user_id)select admin from push_fixture;
grant select,update on push_fixture to authenticated,service_role;
select set_config('request.jwt.claims',json_build_object('sub',owner,'session_id',so)::text,true)from push_fixture;
set local role authenticated;
update push_fixture set team=public.create_team('Push fixture');
do $$begin begin perform public.admin_add_team_member(team,member)from push_fixture;raise exception 'Owner assigned a user without admin';exception when raise_exception then if sqlerrm='Owner assigned a user without admin'then raise;end if;end;end$$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',admin,'session_id',sa)::text,true)from push_fixture;
set local role authenticated;
select public.admin_add_team_member(team,member)from push_fixture;
select public.admin_add_team_member(team,member)from push_fixture;
reset role;
do $$begin if (select count(*)from public.team_members where team_id=(select team from push_fixture)and user_id=(select member from push_fixture))<>1 then raise exception 'Admin membership incorrect';end if;end$$;
select set_config('request.jwt.claims',json_build_object('sub',member,'session_id',sm)::text,true)from push_fixture;
set local role authenticated;
select public.save_push_subscription(jsonb_build_object('endpoint','https://fcm.googleapis.com/test-only','keys',jsonb_build_object('p256dh',repeat('A',87),'auth',repeat('B',22))));
do $$begin
 begin perform public.push_configuration();raise exception 'Private keys exposed';exception when insufficient_privilege then null;end;
 begin perform *from private.push_devices;raise exception 'Other device subscriptions exposed';exception when insufficient_privilege then null;end;
end$$;
reset role;
insert into public.requests(team_id,author_id,title,kind)select team,owner,'Test notification','mission'from push_fixture;
update push_fixture set request=(select id from public.requests where team_id=push_fixture.team);
select set_config('request.jwt.claims','{"role":"service_role"}',true);
set local role service_role;
do $$begin if (select count(*)from public.push_recipients((select request from push_fixture)))<>1 then raise exception 'Recipient filtering failed';end if;end$$;
reset role;
update public.requests set status='cancelled'where id=(select request from push_fixture);
set local role service_role;
do $$begin if exists(select 1 from public.push_recipients((select request from push_fixture)))then raise exception 'Cancelled content shared';end if;end$$;
reset role;
rollback;
select 'PASS: site-admin-only membership, idempotency, private subscriptions and keys, teammate recipient filtering, cancelled exclusion' result;
