begin;
create temporary table avatar_fixture as select gen_random_uuid() author,gen_random_uuid() teammate,gen_random_uuid() stranger,gen_random_uuid() admin,gen_random_uuid() sa,gen_random_uuid() sb,gen_random_uuid() sc,gen_random_uuid() sd,null::uuid team;
insert into auth.users(id) select author from avatar_fixture union all select teammate from avatar_fixture union all select stranger from avatar_fixture union all select admin from avatar_fixture;
insert into public.profiles(id,game_id) select author,'AvatarAuthorTest' from avatar_fixture union all select teammate,'AvatarTeammateTest' from avatar_fixture union all select stranger,'AvatarStrangerTest' from avatar_fixture union all select admin,'AvatarAdminTest' from avatar_fixture;
insert into private.accounts(user_id,game_key,recovery_hash,approved) select id,id::text,'test-only',true from public.profiles where id in(select author from avatar_fixture union all select teammate from avatar_fixture union all select stranger from avatar_fixture union all select admin from avatar_fixture);
insert into auth.sessions(id,user_id) select sa,author from avatar_fixture union all select sb,teammate from avatar_fixture union all select sc,stranger from avatar_fixture union all select sd,admin from avatar_fixture;
insert into private.admins(user_id) select admin from avatar_fixture;
grant select,update on avatar_fixture to authenticated;
select set_config('request.jwt.claims',json_build_object('sub',author,'session_id',sa)::text,true) from avatar_fixture;
set local role authenticated;
update avatar_fixture set team=public.create_team('Avatar fixture');
do $$begin if not exists(select 1 from public.profiles where id=auth.uid() and avatar_preset is not null) then raise exception 'No random default avatar';end if;end$$;
update public.profiles set avatar_preset='creeper',avatar_path=id::text||'/avatar.png' where id=auth.uid();
insert into storage.objects(bucket_id,name,owner_id,metadata) select 'player-avatars',author::text||'/avatar.png',author::text,'{"mimetype":"image/png","size":256}'::jsonb from avatar_fixture;
insert into public.requests(team_id,author_id,title,kind,quantity,item_id,reward,reward_item_id,reward_quantity) select team,author,'Item bounty','item',64,'minecraft:stone','鑽石 × 2','minecraft:diamond',2 from avatar_fixture;
do $$begin
 begin update public.profiles set avatar_path=(select stranger::text||'/avatar.png' from avatar_fixture) where id=auth.uid();raise exception 'Can reference another avatar';exception when check_violation then null;end;
 begin insert into storage.objects(bucket_id,name) select 'player-avatars',stranger::text||'/avatar.png' from avatar_fixture;raise exception 'Can upload to stranger folder';exception when insufficient_privilege then null;end;
 begin update public.profiles set game_id='Forged' where id=auth.uid();raise exception 'Existing profile hardening lost';exception when insufficient_privilege then null;end;
 begin insert into public.requests(team_id,author_id,title,kind,reward_item_id) select team,author,'Half reward','mission','minecraft:diamond' from avatar_fixture;raise exception 'Half reward accepted';exception when check_violation then null;end;
 if not exists(select 1 from public.requests where team_id=(select team from avatar_fixture) and reward_item_id='minecraft:diamond' and reward_quantity=2) then raise exception 'Structured reward not stored';end if;
end$$;
reset role;
insert into public.team_members(team_id,user_id) select team,teammate from avatar_fixture;
select set_config('request.jwt.claims',json_build_object('sub',teammate,'session_id',sb)::text,true) from avatar_fixture;
set local role authenticated;
do $$begin
 if not exists(select 1 from storage.objects where bucket_id='player-avatars' and name=(select author::text||'/avatar.png' from avatar_fixture)) then raise exception 'Teammate cannot read avatar';end if;
 update storage.objects set metadata='{}' where bucket_id='player-avatars' and name=(select author::text||'/avatar.png' from avatar_fixture);if found then raise exception 'Teammate can overwrite avatar';end if;
 begin delete from storage.objects where bucket_id='player-avatars' and name=(select author::text||'/avatar.png' from avatar_fixture);if found then raise exception 'Teammate can delete avatar';end if;exception when insufficient_privilege then null;end;
end$$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',stranger,'session_id',sc)::text,true) from avatar_fixture;
set local role authenticated;
do $$begin if exists(select 1 from storage.objects where bucket_id='player-avatars' and name=(select author::text||'/avatar.png' from avatar_fixture)) then raise exception 'Stranger can read avatar';end if;end$$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',admin,'session_id',sd)::text,true) from avatar_fixture;
set local role authenticated;
do $$begin if not exists(select 1 from storage.objects where bucket_id='player-avatars' and name=(select author::text||'/avatar.png' from avatar_fixture)) then raise exception 'Admin cannot read avatar';end if;end$$;
reset role;
select set_config('request.jwt.claims','{}',true);
set local role anon;
do $$begin if exists(select 1 from storage.objects where bucket_id='player-avatars') then raise exception 'Guest can read avatar metadata';end if;end$$;
reset role;
do $$begin if (select public from storage.buckets where id='player-avatars') then raise exception 'Avatar bucket is public';end if;end$$;
select 'PASS: random preset, private bucket, own updates/uploads, teammate/admin read, no stranger/guest access or teammate writes, structured item reward validation' as result;
rollback;
