begin;
create temporary table feedback_fixture as select gen_random_uuid() author,gen_random_uuid() teammate,gen_random_uuid() admin,gen_random_uuid() sa,gen_random_uuid() sb,gen_random_uuid() sc,null::uuid team,null::uuid feedback;
insert into auth.users(id) select author from feedback_fixture union all select teammate from feedback_fixture union all select admin from feedback_fixture;
insert into public.profiles(id,game_id) select author,'FeedbackAuthorTest' from feedback_fixture union all select teammate,'FeedbackTeammateTest' from feedback_fixture union all select admin,'FeedbackAdminTest' from feedback_fixture;
insert into private.accounts(user_id,game_key,recovery_hash,approved) select id,id::text,'test-only',true from public.profiles where id in(select author from feedback_fixture union all select teammate from feedback_fixture union all select admin from feedback_fixture);
insert into auth.sessions(id,user_id) select sa,author from feedback_fixture union all select sb,teammate from feedback_fixture union all select sc,admin from feedback_fixture;
insert into private.admins(user_id) select admin from feedback_fixture;
grant select,update on feedback_fixture to authenticated;
select set_config('request.jwt.claims',json_build_object('sub',author,'session_id',sa)::text,true) from feedback_fixture;
set local role authenticated;
update feedback_fixture set team=public.create_team('Feedback fixture');
with submitted as (insert into public.feedback(author_id,title,body,kind) select author,'A player suggestion','Expected behavior','idea' from feedback_fixture returning id) update feedback_fixture set feedback=(select id from submitted);
insert into public.requests(team_id,author_id,title,kind,quantity,item_id,reward) select team,author,'募集石頭','item',64,'minecraft:stone','2 顆鑽石' from feedback_fixture;
do $$begin
 if not exists(select 1 from public.feedback where id=(select feedback from feedback_fixture) and status='not_started') then raise exception 'Feedback not submitted';end if;
 begin update public.feedback set status='completed';raise exception 'Player can change status';exception when insufficient_privilege then null;end;
 begin insert into public.feedback(author_id,title,body) select teammate,'Spoofed','Spoof' from feedback_fixture;raise exception 'Can spoof author';exception when insufficient_privilege then null;end;
 begin perform public.review_feedback(feedback,'completed','forged') from feedback_fixture;raise exception 'Team admin can review website feedback';exception when raise_exception then if sqlerrm='Team admin can review website feedback' then raise;end if;end;
 begin insert into public.requests(team_id,author_id,title,kind) select team,author,repeat('x',33),'mission' from feedback_fixture;raise exception 'Long title accepted';exception when raise_exception then if sqlerrm='Long title accepted' then raise;end if;end;
 begin insert into public.requests(team_id,author_id,title,kind) select team,author,'Missing quantity','item' from feedback_fixture;raise exception 'Missing quantity accepted';exception when raise_exception then if sqlerrm='Missing quantity accepted' then raise;end if;end;
 if not exists(select 1 from public.requests where team_id=(select team from feedback_fixture) and quantity=64 and reward='2 顆鑽石') then raise exception 'Bounty not retained';end if;
end$$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',teammate,'session_id',sb)::text,true) from feedback_fixture;
set local role authenticated;
do $$begin if exists(select 1 from public.feedback where id=(select feedback from feedback_fixture)) then raise exception 'Other player can read feedback';end if;end$$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',admin,'session_id',sc)::text,true) from feedback_fixture;
set local role authenticated;
select public.review_feedback(feedback,'reviewed','Reviewed'),public.review_feedback(feedback,'in_progress','Working'),public.review_feedback(feedback,'completed','Published') from feedback_fixture;
do $$begin if not exists(select 1 from public.feedback where id=(select feedback from feedback_fixture) and status='completed' and admin_reply='Published') then raise exception 'Admin cannot review feedback';end if;end$$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',author,'session_id',sa)::text,true) from feedback_fixture;
set local role authenticated;
do $$begin if not exists(select 1 from public.feedback where id=(select feedback from feedback_fixture) and status='completed' and admin_reply='Published') then raise exception 'Author cannot see result';end if;end$$;
reset role;
set local role anon;
do $$begin begin perform count(*) from public.feedback;raise exception 'Guest can read feedback';exception when insufficient_privilege then null;end;end$$;
reset role;
select 'PASS: private feedback, no forged author/status, server admin review, player result visibility, bounty persistence, short title and quantity checks' as result;
rollback;
