begin;
create temporary table team_fixture as select gen_random_uuid() creator,gen_random_uuid() member,gen_random_uuid() server_admin,gen_random_uuid() sa,gen_random_uuid() sb,gen_random_uuid() sc,null::uuid team,null::text code;
insert into auth.users(id) select creator from team_fixture union all select member from team_fixture union all select server_admin from team_fixture;
insert into public.profiles(id,game_id) select creator,'TeamCreatorTest' from team_fixture union all select member,'TeamMemberTest' from team_fixture union all select server_admin,'ServerAdminTest' from team_fixture;
insert into private.accounts(user_id,game_key,recovery_hash,approved) select id,id::text,'test-only',true from public.profiles where id in (select creator from team_fixture union all select member from team_fixture union all select server_admin from team_fixture);
insert into auth.sessions(id,user_id) select sa,creator from team_fixture union all select sb,member from team_fixture union all select sc,server_admin from team_fixture;
insert into private.admins(user_id) select server_admin from team_fixture;
grant select,update on team_fixture to authenticated;
select set_config('request.jwt.claims',json_build_object('sub',creator,'session_id',sa)::text,true) from team_fixture;
set local role authenticated;
update team_fixture set team=public.create_team('Role fixture');
update team_fixture set code=public.team_invite(team);
do $$begin if not exists(select 1 from public.team_members where team_id=(select team from team_fixture) and user_id=auth.uid() and role='admin') then raise exception 'Creator not admin';end if;end$$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',member,'session_id',sb)::text,true) from team_fixture;
set local role authenticated;
select public.join_team(code) from team_fixture;
do $$begin
 begin perform public.team_invite(team) from team_fixture;raise exception 'Member read hidden invite';exception when raise_exception then if sqlerrm='Member read hidden invite' then raise;end if;end;
 begin perform public.manage_team(team,'share_invite',null,'true') from team_fixture;raise exception 'Member can manage team';exception when raise_exception then if sqlerrm='Member can manage team' then raise;end if;end;
 begin update public.team_members set role='admin' where user_id=auth.uid();raise exception 'Member can forge role';exception when insufficient_privilege then null;end;
 begin perform code from private.team_invite_codes;raise exception 'Private invite table exposed';exception when insufficient_privilege then null;end;
end$$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',creator,'session_id',sa)::text,true) from team_fixture;
set local role authenticated;
select public.manage_team(team,'share_invite',null,'true') from team_fixture;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',member,'session_id',sb)::text,true) from team_fixture;
set local role authenticated;
do $$begin if (select public.team_invite(team) from team_fixture) is distinct from (select code from team_fixture) then raise exception 'Shared invite unavailable';end if;
 begin perform public.team_invite(team,true) from team_fixture;raise exception 'Member rotated invite';exception when raise_exception then if sqlerrm='Member rotated invite' then raise;end if;end;
end$$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',creator,'session_id',sa)::text,true) from team_fixture;
set local role authenticated;
select public.manage_team(team,'role',member,'admin') from team_fixture;
select public.manage_team(team,'role',creator,'member') from team_fixture;
do $$begin if private.can_manage_team((select team from team_fixture)) then raise exception 'Demotion not effective';end if;end$$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',member,'session_id',sb)::text,true) from team_fixture;
set local role authenticated;
do $$begin
 begin perform public.manage_team(team,'role',member,'member') from team_fixture;raise exception 'Last admin removed';exception when raise_exception then if sqlerrm='Last admin removed' then raise;end if;end;
 begin perform public.leave_team(team) from team_fixture;raise exception 'Last admin abandoned members';exception when raise_exception then if sqlerrm='Last admin abandoned members' then raise;end if;end;
end$$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',server_admin,'session_id',sc)::text,true) from team_fixture;
set local role authenticated;
do $$begin if not exists(select 1 from public.teams where id=(select team from team_fixture)) or not private.can_manage_team((select team from team_fixture)) then raise exception 'Server admin cannot manage other team';end if;end$$;
select public.manage_team(team,'role',member,'member') from team_fixture;
select public.manage_team(team,'role',creator,'admin') from team_fixture;
select public.manage_team(team,'share_invite',null,'false') from team_fixture;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',member,'session_id',sb)::text,true) from team_fixture;
set local role authenticated;
select public.leave_team(team) from team_fixture;
do $$begin if exists(select 1 from public.teams where id=(select team from team_fixture)) then raise exception 'Departed member still reads team';end if;end$$;
reset role;
select 'PASS: creator role, invite visibility, member denial, promotion/demotion, last admin protection, server admin override, leave revokes access' as result;
rollback;
